<?php
/** @var SellOrder $data */
?>
<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>

    /* override styles when printing */
    @media print {
        body {
            margin: 0;
            padding: 0;
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        }

        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
            font-weight: bold;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }


    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
        font-family: fangsong;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }


    .top-sheet-item-list tbody th,
    .top-sheet-item-list tbody td,
    .top-sheet-footer td,
    .top-sheet-footer th {
        border: 1px solid black;
        font-family: fangsong;
    }

    .page-break-div {
        page-break-after: always !important;
    }

    .pageNumber::before {
        content: "Page " counter(page);
        position: absolute;
        bottom: 0;
        width: 100%;
        text-align: center;
    }
</style>

<div class="card card-primary  table-responsive">
    <div class="card-header">
        <h3 class="card-title">
            <?php
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                    'title' => ' ', //the title of the document. Defaults to the HTML title
                    'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                    'text' => '', //text which will appear beside the print icon. Defaults to NULL
                    'element' => '.printAllTableForThisReport', //the element to be printed.
                    'exceptions' => array(//the element/s which will be ignored
                            '.summary',
                            '.search-form',
                            '#excludeDiv',
                    ),
                    'publishCss' => FALSE, //publish the CSS for the whole page?
                    'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                    'alt' => 'print', //text which will appear if image can't be loaded
                    'debug' => true, //enable the debugger to see what you will get
                    'id' => 'print-div'         //id of the print link
            ));
            echo "</div><br><br><br>";
            ?>
        </h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <div class="printAllTableForThisReport">
            <?php
            foreach ($data as $item) {
                $showProfitLossSummary = isset($show_profit) ? $show_profit : false;
                $footerRowSpan = 9;
                $footerColspan = 5;
                if ($showProfitLossSummary) {
                    $footerColspan = 6;
                }
                if ($item) {
                    $customer = Customers::model()->findByPk($item->customer_id);
                    ?>
                    <div style="width: 100%; min-height: 80px;">
                        <?php
                        if (isset($preview_type)) {
                            if ($preview_type == SellOrder::NORMAL_PAD_PRINT) {
                                $this->renderPartial('application.modules.sell.views.sellOrder.pad_header');
                            } else {
                                $this->renderPartial('application.modules.sell.views.sellOrder.without_pad_header');
                            }
                        } else {
                            $this->renderPartial('application.modules.sell.views.sellOrder.without_pad_header');
                        }
                        ?>
                        <div style="width: 100%; float: left; clear: right; margin-bottom: 10px; text-align: left">
                            <div style="width: 50%; float: left; clear: right; font-size: 13px;">
                                <h5 style="margin-bottom: 5px; font-size: 14px; font-weight: bold;">Customer
                                    Details</h5>
                                <?php
                                $customer_name = $customer ? $customer->company_name : 'N/A';
                                if ($customer) {
                                    $details = [];

                                    if (!empty($customer->company_name)) {
                                        $details[] = $customer->company_name;
                                    }

                                    if (!empty($customer->company_address)) {
                                        $details[] = $customer->company_address;
                                    }

                                    if (!empty($customer->owner_mobile_no)) {
                                        $details[] = 'Phone: ' . $customer->owner_mobile_no;
                                    }

                                    if (!empty($customer->trn_no)) {
                                        $details[] = 'TRN: ' . $customer->trn_no;
                                    }

                                    echo implode('<br>', $details);
                                } else {
                                    echo 'N/A';
                                }
                                ?>
                            </div>

                            <div style="width: 50%; float: left; text-align: right; vertical-align: bottom; margin-top: 20px;">
                                <b>Date:</b>
                                <?= date('d.m.Y', strtotime($item->date)) ?>
                                <br>
                                <b>Invoice ID:</b>
                                #<?= "$item->id" ?>
                                <br>
                                <b>Invoice No:</b>
                                #<?= "$item->so_no" ?>
                                <br>
                                <?php
                                if ($showProfitLossSummary) {
                                    ?>
                                    <span style="border: 1px solid black; padding: 8px;">
                                    <b style="font-size: 20px;">P/L: <span id="profitLossText_<?= $item->id ?>"></span></b>
                                            </span>
                                    <?php
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                    <table style="width: 100%; border-collapse: collapse; font-size: 12px;" class="item-list">
                        <thead>
                        <tr>
                            <td style="text-align: center; width: 2%; border: 1px solid black;">#</td>
                            <td style="text-align: center; border: 1px solid black;">Description</td>
                            <td style="text-align: center;  width: 10%; border: 1px solid black;">Qty</td>
                            <td style="text-align: center;  width: 10%; border: 1px solid black;">Price</td>
                            <td style="text-align: center; width: 15%; border: 1px solid black;">Total</td>
                            <?php
                            if ($showProfitLossSummary) {
                                ?>
                                <td style="text-align: center; width: 10%;">N.I</td>
                                <?php
                            }
                            ?>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $vat = $item->vat_amount;
                        $vat_percentage = $item->vat_percentage;
                        $delivery_charge = $item->delivery_charge;
                        $discount_amount = $item->discount_amount;
                        $road_fee = $item->road_fee;
                        $damage = $item->damage_value;
                        $sr_commission = $item->sr_commission;
                        $criteria = new CDbCriteria();
                        $criteria->select = "pm.model_name, pm.code, pm.image, sum(t.qty) as qty, t.amount, t.discount_amount,
                                            t.note, sum(t.row_total) as row_total,  sum(costing) as costing,
                                            GROUP_CONCAT(product_sl_no ORDER BY product_sl_no SEPARATOR ', ') as product_sl_no, 
                                            GROUP_CONCAT(t.warranty ORDER BY t.warranty SEPARATOR ', ') as warranty,
                                            pm.description";
                        $criteria->join = " INNER JOIN prod_models pm on t.model_id = pm.id ";
                        $criteria->addColumnCondition(['t.sell_order_id' => $item->id]);
                        $criteria->group = "pm.id";
                        $criteria->order = "pm.item_id DESC, pm.model_name ASC";
                        $data2 = SellOrderDetails::model()->findAll($criteria);
                        $row_total = 0;
                        $totalCosting = 0;
                        if ($data2) {
                            $i = 1;
                            foreach ($data2 as $dt) {
                                ?>
                                <tr>
                                    <td style="text-align: center;"><?= $i++ ?></td>
                                    <td style="text-align: left; border: 1px solid black;">
                                        <?= $dt->model_name ?>
                                    </td>
                                    <td style="text-align: center;"><?= number_format($dt->qty) ?></td>
                                    <td style="text-align: right;"> TK <?= number_format($dt->amount, 4) ?></td>
                                    <td style="text-align: right;">
                                        TK <?= number_format($dt->row_total, 4) ?></td>
                                    <?php
                                    if ($showProfitLossSummary) {
                                        $netIncome = $dt->row_total - ($dt->costing + $dt->discount_amount);
                                        ?>
                                        <td style="text-align: right;"> TK <?= number_format($netIncome, 4) ?>
                                        </td>
                                        <?php
                                    }
                                    ?>
                                </tr>
                                <?php
                                $row_total += $dt->row_total;
                                $totalCosting += ($dt->costing);
                            }
                            if ($totalCosting != $item->costing) {
                                $item->costing = $totalCosting;
                                $item->save();
                            }
                        } else {
                            ?>
                            <tr>
                                <td colspan="6">
                                    <div class="alert alert-danger" role="alert">
                                        No item found
                                    </div>
                                </td>
                            </tr>
                            <?php
                        }
                        $actualGrandTotal = ROUND((($row_total + $vat + $delivery_charge) - $discount_amount), 2);
                        if ($actualGrandTotal != $item->grand_total) {
                            $item->grand_total = $actualGrandTotal;
                            $item->total_due = $actualGrandTotal;
                            $item->save();
                        }
                        ?>
                        <tr>
                            <td rowspan="<?= $footerRowSpan ?>>" colspan="2"
                                style="border: none; background: white; text-align: left; letter-spacing: 1px; font-weight: bold;">
                                <div>In Words: <i>BDT
                                        <?php
                                        $amountInWord = new AmountInWord();
                                        $inword = $amountInWord->convert(intval($row_total));
                                        if ($amountInWord->convertFloat($row_total)) {
                                            $inword .= $amountInWord->convertFloat($row_total) . ' Taka Only';
                                        } else {
                                            $inword .= ' Only';
                                        }
                                        echo $inword;
                                        ?>
                                    </i>
                                </div>
                                <br><br>
                                <div style="font-weight: normal;">
                                    Note: <?= $item->order_note ?>
                                </div>
                            </td>
                            <td colspan="2" style="border: none; background: white;">Sub Total</td>
                            <td style="text-align: right; border: none;">
                                TK <?= number_format($row_total, 4) ?></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="border: none; background: white;">Vat
                                (<?= number_format($vat_percentage, 2) ?>%) (+)
                            </td>
                            <td style="text-align: right; border: none;">TK <?= number_format($vat, 4) ?></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="border: none; background: white;">Delivery Charge (+)</td>
                            <td style="text-align: right; border: none;">
                                TK <?= number_format($delivery_charge, 4) ?></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="border: none; background: white;">Discount (-)</td>
                            <td style="text-align: right; border: none;">TK
                                (-<?= number_format($discount_amount, 4) ?>
                                )
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" style="border: none; background: white;">Road Fee (-)</td>
                            <td style="text-align: right; border: none;">TK
                                (-<?= number_format($road_fee, 4) ?>
                                )
                            </td>
                        </tr>

                        <tr>
                            <td colspan="2" style="border: none; background: white;">Damage (-)</td>
                            <td style="text-align: right; border: none;">TK
                                (-<?= number_format($damage, 4) ?>
                                )
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" style="border: none; background: white;">SR Commision (-)</td>
                            <td style="text-align: right; border: none;">TK
                                (-<?= number_format($sr_commission, 4) ?>
                                )
                            </td>
                        </tr>

                        <tr style="font-weight: bold;">
                            <td colspan="2" style="border: none; background: white;">
                                <div style="height: 1px; width: 100%; border: 1px solid black;"></div>
                                Net payable amount
                            </td>
                            <td style="text-align: right; border: none;">
                                <div style="height: 1px; width: 100%; border: 1px solid black;"></div>
                                TK <?= number_format($item->grand_total, 4) ?></td>
                        </tr>
                        <?php
                        $specialCustomeIdArr = [0];
                        if (!in_array($item->customer_id, $specialCustomeIdArr)) {
                            ?>

                            <tr>
                                <td colspan="2" style="border: none; background: white;">
                                    Previous Due Amount
                                </td>
                                <td style="text-align: right; border: none;">
                                    <?php
                                    $criteria = new CDbCriteria();
                                    $criteria->select = "SUM(grand_total) as grand_total";
                                    $criteria->addColumnCondition(['t.customer_id' => $item->customer_id]);
                                    $criteria->addCondition("id != '$item->id' AND date <= '$item->date'");
                                    $sellOrder = SellOrder::model()->findByAttributes([], $criteria);
                                    $prev_sell_value = $sellOrder ? $sellOrder->grand_total : 0;

                                    //                                    echo "<span style='color: red;'>S: TK" . number_format($prev_sell_value, 2) . "... </span><br>";

                                    $criteriaMr = new CDbCriteria();
                                    $criteriaMr->select = "SUM(amount+discount) as amount";
                                    $criteriaMr->addColumnCondition(['t.customer_id' => $item->customer_id]);
                                    $criteriaMr->addCondition("date < '$item->date'");
                                    $moneyReceipt = MoneyReceipt::model()->findByAttributes([], $criteriaMr);
                                    $prev_collection = $moneyReceipt ? $moneyReceipt->amount : 0;
                                    //                                    echo "<span style='color: green;'>C: TK" . number_format($prev_collection, 2) . "... </span><br>";

                                    $criteriaReturn = new CDbCriteria();
                                    $criteriaReturn->select = "SUM(return_amount) as return_amount";
                                    $criteriaReturn->addColumnCondition(['t.customer_id' => $item->customer_id]);
                                    $criteriaReturn->addCondition("return_date <= '$item->date'");
                                    $sellReturn = SellReturn::model()->findByAttributes([], $criteriaReturn);
                                    $prev_return = $sellReturn ? $sellReturn->return_amount : 0;
                                    //                                    echo "<span style='color: violet;'>R: TK" . number_format($prev_return, 2) . "... </span><br>";

                                    $criteriaMr1 = new CDbCriteria();
                                    $criteriaMr1->select = "SUM(amount) as amount, SUM(discount) as discount";
                                    $criteriaMr1->addColumnCondition(['t.customer_id' => $item->customer_id, 'date' => $item->date]);
                                    $moneyReceipt1 = MoneyReceipt::model()->findByAttributes([], $criteriaMr1);
                                    $current_collection = $moneyReceipt1 ? $moneyReceipt1->amount : 0;
                                    $current_collection = $current_collection > 0 ? $current_collection : 0;
                                    $current_collection_discount = $moneyReceipt1 ? $moneyReceipt1->discount : 0;

                                    $criteriaReturn1 = new CDbCriteria();
                                    $criteriaReturn1->select = "SUM(return_amount) as return_amount";
                                    $criteriaReturn1->addColumnCondition(['t.customer_id' => $item->customer_id, 'return_date' => $item->date]);
                                    $sellReturn1 = SellReturn::model()->findByAttributes([], $criteriaReturn1);
                                    $current_return = $sellReturn1 ? $sellReturn1->return_amount : 0;

                                    $previous_due_amount = $prev_sell_value - $prev_collection - $prev_return;

                                    $current_due_amount = $previous_due_amount + $item->grand_total - $current_collection - $current_collection_discount - $current_return;
                                    ?>
                                    TK <?= number_format($previous_due_amount, 2) ?>
                                </td>
                            </tr>
                            <tr style="font-weight: bold;">
                                <td colspan="2" style="border: none; background: white;"></td>
                                <td colspan="2" style="border: none;">
                                    Current Paid Amount
                                </td>
                                <td style="text-align: right; border: none;">
                                    TK <?= number_format($current_collection, 2) ?></td>
                            </tr>
                            <?php
                            if ($current_return > 0) {
                                ?>
                                <tr style="">
                                    <td colspan="2" style="border: none; background: white;"></td>
                                    <td colspan="2" style="border: none;">
                                        Current Return Amount
                                    </td>
                                    <td style="text-align: right; border: none;">
                                        TK <?= number_format($current_return, 2) ?></td>
                                </tr>
                                <?php
                            }
                            ?>
                            <tr>
                                <td colspan="2" style="border: none; background: white;"></td>
                                <td colspan="2" style="border: none;">
                                    Cash Discount
                                </td>
                                <td style="text-align: right; border: none;">
                                    TK
                                    (-<?= number_format($current_collection_discount > 0 ? $current_collection_discount : 0, 2) ?>
                                    )
                                </td>
                            </tr>
                            <tr style="font-weight: bold;">
                                <td colspan="2" style="border: none; background: white;"></td>
                                <td colspan="2" style="border: none;">
                                    <div style="height: 1px; width: 100%; border: 1px solid black;"></div>
                                    Current Due Amount
                                </td>
                                <td style="text-align: right; border: none;">
                                    <div style="height: 1px; width: 100%; border: 1px solid black;"></div>
                                    TK <?= number_format($current_due_amount, 2) ?></td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>

                    <div style="width: 100%; float: left; clear: right; height: 150px; font-size: 12px; margin-top: 20px;">
                        <div style="height: 30px; text-align: left; width: 100%; float: left; clear: right;">
                            By signing this document, the customer agrees to he services and conditions
                            described in this document.
                        </div>
                        <br>
                        <div style="width: 100%; float: left; clear:right;">

                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <span style="text-decoration: underline; font-weight: bold;"><?= strtoupper(Yii::app()->params['company']['name']) ?></span>
                            </div>
                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <span style="text-decoration: underline; font-weight: bold;"><?= $customer_name ?></span>
                            </div>
                        </div>
                        <div style="height: 50px; width: 100%; float: left; clear: right; margin-top: 40px;">
                            <div style="width: 50%; float: left; clear: right; margin: auto; display: flex; flex-direction: column; justify-content: center; align-items: center;">
                                <div style="font-weight: bold; text-transform: uppercase;">
                                    &nbsp;
                                </div>
                                <div style="text-decoration: overline;"><?= date('F d, Y') ?></div>
                            </div>

                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <div>(&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    )
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="page-break-div"></div>

                    <script>
                        <?php
                        if ($showProfitLossSummary){
                        ?>
                        var profitLoss = <?= $row_total - $totalCosting - $discount_amount ?>;
                        // if profit then show green color else show red color
                        if (profitLoss > 0) {
                            // use pure javascript instead of jquery
                            //$('#profitLossText_<?php //= $item->id ?>//').css('color', 'green');
                            document.getElementById('profitLossText_<?= $item->id ?>').style.color = 'green';

                        } else {
                            //$('#profitLossText_<?php //= $item->id ?>//').css('color', 'red');
                            document.getElementById('profitLossText_<?= $item->id ?>').style.color = 'red';
                        }
                        //$('#profitLossText_<?php //= $item->id ?>//').text(profitLoss.toFixed(2));

                        document.getElementById('profitLossText_<?= $item->id ?>').innerHTML = profitLoss.toFixed(2);

                        <?php
                        }
                        ?>
                    </script>
                <?php
                } else {
                ?>
                    <div class="alert alert-danger" role="alert">
                        No result found!
                    </div>
                    <?php
                }
            }
            ?>

        </div>
    </div>
</div>