<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>

    /* override styles when printing */
    @media print {
        body {
            margin: 0;
            padding: 0;
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        }

        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
            font-weight: bold;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }


    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
        font-family: fangsong;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }


    .top-sheet-item-list tbody th,
    .top-sheet-item-list tbody td,
    .top-sheet-footer td,
    .top-sheet-footer th {
        border: 1px solid black;
        font-family: fangsong;
    }

    .page-break-div {
        page-break-after: always !important;
    }
</style>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Preview</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <!--            <button type="button" class="btn btn-tool" data-card-widget="remove">-->
            <!--                <i class="fa fa-times"></i>-->
            <!--            </button>-->
        </div>
    </div>
    <div class="card-body">
        <div style="width: 100%">
            <?php
            if ($data) {
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => FALSE, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div><br><br><br>";


            $customer = Customers::model()->findByPk($data->customer_id);
            ?>
            <div class='printAllTableForThisReport' style="width: 8.5in;">
                <div class="page-begaining">
                    <div class="header" id="pageHeader" style="width: 100%; min-height: 80px;">
                        <?php
                        if (isset($preview_type)) {
                            if ($preview_type == SellOrder::NORMAL_PAD_PRINT) {
                                $this->renderPartial('pad_header');
                            } else {
                                $this->renderPartial('without_pad_header');
                            }
                        } else {
                            $this->renderPartial('without_pad_header');
                        }
                        ?>
                        <div style="width: 100%; float: left; clear: right; margin-bottom: 10px;">
                            <div style="width: 50%; float: left; clear: right;">
                                <h5>Customer Details</h5>
                                <?php
                                $customer_name = $customer_zip = $customer_city = $customer_state = $customer_phone = $customer_trn_no = "N/A";
                                if ($customer) {
                                    $customer_name = $customer->company_name;
                                    $customer_zip = $customer->zip;
                                    $customer_city = $customer->city;
                                    $customer_state = $customer->state;
                                    $customer_phone = $customer->owner_mobile_no;
                                    $customer_trn_no = $customer->trn_no;
                                }
                                echo "$customer_name<br>";
                                echo ($customer_zip || $customer_state) ? "$customer_zip, $customer_state<br>" : "";
                                echo ($customer_city) ? "$customer_city<br>" : "";
                                echo ($customer_phone) ? "$customer_phone<br>" : "";
                                echo ($customer_trn_no) ? "$customer_trn_no<br>" : "";
                                ?>
                            </div>
                            <div style="width: 50%; float: left; text-align: right; vertical-align: bottom; margin-top: 20px;">
                                <b>Date:</b>
                                <?= date('d.m.Y', strtotime($data->date)) ?>
                                <br>

                                <b>Invoice No:</b>
                                <?= "$data->so_no" ?>
                                <br>
                            </div>
                        </div>
                    </div>
                    <table style="width: 100%; border-collapse: collapse; font-size: 12px;" class="item-list">

                        <tr>
                            <td style="text-align: center; width: 2%;">#</td>
                            <td style="text-align: center;">Description</td>
                            <td style="text-align: center; display: none;">Color</td>
                            <td style="text-align: center;  width: 10%;">Qty</td>
                            <td style="text-align: center;  width: 10%;">Price</td>
                            <td style="text-align: center; width: 15%;">Total</td>
                        </tr>
                        <tbody>
                        <?php
                        $vat = $data->vat_amount;
                        $vat_percentage = $data->vat_percentage;
                        $delivery_charge = $data->delivery_charge;
                        $discount_amount = $data->discount_amount;
                        $criteria = new CDbCriteria();
                        $criteria->select = "pm.model_name, pm.code, pm.image, sum(t.qty) as qty, t.amount, 
                                            t.note, sum(t.row_total) as row_total, 
                                            GROUP_CONCAT(product_sl_no ORDER BY product_sl_no SEPARATOR ', ') as product_sl_no, 
                                            GROUP_CONCAT(t.warranty ORDER BY t.warranty SEPARATOR ', ') as warranty,
                                            pm.description";
                        $criteria->join = " INNER JOIN prod_models pm on t.model_id = pm.id ";
                        $criteria->addColumnCondition(['t.sell_order_id' => $data->id]);
                        $criteria->group = "pm.id";
                        $criteria->order = "pm.item_id DESC, pm.model_name ASC";
                        $data2 = SellOrderDetails::model()->findAll($criteria);
                        $row_total = 0;
                        if ($data2) {
                            $i = 1;
                            foreach ($data2 as $dt) {
                                ?>
                                <tr>
                                    <td style="text-align: center;"><?= $i++ ?></td>
                                    <td>
                                        <?= $dt->model_name ?>
                                        <?php
                                        if ($dt->note) {
                                            echo "<br>" . nl2br($dt->note);
                                        }
                                        if (strlen($dt->product_sl_no ?? '') > 0) {
                                            echo "<br><b>SL:</b>$dt->product_sl_no";
                                        }
                                        if (strlen((string)$dt->warranty) > 0) {
                                            $dataArrayWarranty = explode(', ', $dt->warranty);
                                            $dataArrayWarrantyUnique = array_unique($dataArrayWarranty);
                                            $dataArrayWarrantyUnique = array_values($dataArrayWarrantyUnique);
//                                            print_r($dataArrayWarrantyUnique);
                                            $warranty =  implode(', ', $dataArrayWarrantyUnique);
                                            echo "<br><b>Warranty: </b> <i>$warranty Month</i>";
                                        }
                                        ?>
                                    </td>
                                    <td style="display: none;"><?= $dt->color ?></td>
                                    <td style="text-align: center;"><?= number_format($dt->qty) ?></td>
                                    <td style="text-align: right;"> TK <?= number_format($dt->amount, 2) ?></td>
                                    <td style="text-align: right;"> TK <?= number_format($dt->row_total, 2) ?></td>
                                </tr>
                                <?php
                                $row_total += $dt->row_total;
                            }
                        } else {
                            ?>
                            <tr>
                                <td colspan="6">
                                    <div class="alert alert-danger" role="alert">
                                        No item found
                                    </div>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                        <tr>
                            <td rowspan="5" colspan="2" style="border: none;">
                                <div>Total Amount In Words:</div>
                                <div>BDT:
                                    <?php
                                    $amountInWord = new AmountInWord();
                                    $inword = $amountInWord->convert(intval($row_total));
                                    if ($amountInWord->convertFloat($row_total)) {
                                        $inword .= $amountInWord->convertFloat($row_total) . ' Only';
                                    } else {
                                        $inword .= ' Only';
                                    }
                                    echo $inword;
                                    ?>
                                </div>
                            </td>
                            <td colspan="2" style="border: none;">Sub Total</td>
                            <td style="text-align: right; border: none;">TK <?= number_format($row_total, 2) ?></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="border: none;">Vat (<?= number_format($vat_percentage, 2) ?>%)</td>
                            <td style="text-align: right; border: none;">TK <?= number_format($vat, 2) ?></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="border: none;">Delivery Charge</td>
                            <td style="text-align: right; border: none;">
                                TK <?= number_format($delivery_charge, 2) ?></td>
                        </tr>
                        <tr>
                            <td colspan="2" style="border: none;">Discount</td>
                            <td style="text-align: right; border: none;">TK (-<?= number_format($discount_amount, 2) ?>
                                )
                            </td>
                        </tr>
                        <tr style="font-weight: bold;">
                            <td colspan="2" style="border: none;">
                                <div style="height: 1px; width: 100%; border: 1px solid black;"></div>
                                Net payable amount
                            </td>
                            <td style="text-align: right; border: none;">
                                <div style="height: 1px; width: 100%; border: 1px solid black;"></div>
                                TK <?= number_format($data->grand_total, 2) ?></td>
                        </tr>
                        <?php
                        if ($data->customer_id != 39) {
                            ?>

                            <tr>
                                <td colspan="2" style="border: none; background: white;"></td>
                                <td colspan="2" style="border: none;">
                                    Previous Due Amount
                                </td>
                                <td style="text-align: right; border: none;">
                                    <?php
                                    $criteria = new CDbCriteria();
                                    $criteria->select = "SUM(grand_total) as grand_total";
                                    $criteria->addColumnCondition(['t.customer_id' => $data->customer_id]);
                                    $criteria->addCondition("id != '$data->id'");
                                    $sellOrder = SellOrder::model()->findByAttributes([], $criteria);
                                    $prev_sell_value = $sellOrder ? $sellOrder->grand_total : 0;

                                    $criteriaMr = new CDbCriteria();
                                    $criteriaMr->select = "SUM(amount + discount) as amount";
                                    $criteriaMr->addColumnCondition(['t.customer_id' => $data->customer_id]);
                                    $criteriaMr->addCondition("invoice_id != '$data->id' ");
                                    $moneyReceipt = MoneyReceipt::model()->findByAttributes([], $criteriaMr);
                                    $prev_collection = $moneyReceipt ? $moneyReceipt->amount : 0;

                                    $criteriaMr1 = new CDbCriteria();
                                    $criteriaMr1->select = "SUM(amount) as amount, SUM(discount) as discount";
                                    $criteriaMr1->addColumnCondition(['t.customer_id' => $data->customer_id, 'invoice_id' => $data->id]);
                                    $moneyReceipt1 = MoneyReceipt::model()->findByAttributes([], $criteriaMr1);
                                    $current_collection = $moneyReceipt1 ? $moneyReceipt1->amount : 0;
                                    $current_collection = $current_collection > 0 ? $current_collection : 0;
                                    $current_collection_discount = $moneyReceipt1 ? $moneyReceipt1->discount : 0;

                                    $previous_due_amount = $prev_sell_value - $prev_collection;

                                    $current_due_amount = $previous_due_amount + $data->grand_total - $current_collection - $current_collection_discount;
                                    ?>
                                    TK <?= number_format($previous_due_amount, 2) ?></td>
                            </tr>
                            <tr style="font-weight: bold;">
                                <td colspan="2" style="border: none;"></td>
                                <td colspan="2" style="border: none;">
                                    Current Paid Amount
                                </td>
                                <td style="text-align: right; border: none;">
                                    TK <?= number_format($current_collection, 2) ?></td>
                            </tr>
                            <tr>
                                <td colspan="2" style="border: none;"></td>
                                <td colspan="2" style="border: none;">
                                    Cash Discount
                                </td>
                                <td style="text-align: right; border: none;">
                                    TK (-<?= number_format($current_collection_discount > 0 ? $current_collection_discount : 0, 2) ?>)</td>
                            </tr>
                            <tr style="font-weight: bold;">
                                <td colspan="2" style="border: none;"></td>
                                <td colspan="2" style="border: none;">
                                    <div style="height: 1px; width: 100%; border: 1px solid black;"></div>
                                    Current Due Amount
                                </td>
                                <td style="text-align: right; border: none;">
                                    <div style="height: 1px; width: 100%; border: 1px solid black;"></div>
                                    TK <?= number_format($current_due_amount, 2) ?></td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>

                    <div style="width: 100%; float: left; clear: right; height: 150px; font-size: 12px; margin-top: 20px;">
                        <div style="height: 30px; text-align: left; width: 100%; float: left; clear: right;">
                            By signing this document, the customer agrees to he services and conditions
                            described in this document.
                        </div>

                        <br>
                        <div style="width: 100%; float: left; clear:right;">

                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <span style="text-decoration: underline; font-weight: bold;">The Mihan Engineers (TMEBD)</span>
                            </div>
                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <span style="text-decoration: underline; font-weight: bold;"><?= $customer_name ?></span>
                            </div>
                        </div>
                        <div style="height: 50px; width: 100%; float: left; clear: right; margin-top: 40px;">
                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <div><?= date('F d, Y') ?></div>
                            </div>
                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <div>(&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    )
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
                } else {
                    ?>
                    <div class="alert alert-danger" role="alert">
                        No result found!
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>