<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>
    /* override styles when printing */
    @media print {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }

    @page {
        size: 8.27in 11.69in;  /* width height A4 size paper */
    }


    .item-list thead th,
    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
    }

    .heading td {
        min-height: 25px !important;
    }

    .heading tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }
</style>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Preview</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <!--            <button type="button" class="btn btn-tool" data-card-widget="remove">-->
            <!--                <i class="fa fa-times"></i>-->
            <!--            </button>-->
        </div>
    </div>
    <div class="card-body">
        <div style="width: 100%">
            <?php
            if ($data) {
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => FALSE, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div>";
            $yourCompany = YourCompany::model()->findByAttributes(['is_active' => YourCompany::ACTIVE]);
            $company_name = $company_location = $company_road = $company_house = $company_contact = $company_email = $company_web = $company_trn_no = "N/A";
            if ($yourCompany) {
                $company_name = $yourCompany->company_name;
                $company_location = $yourCompany->location;
                $company_road = $yourCompany->road;
                $company_house = $yourCompany->house;
                $company_contact = $yourCompany->contact;
                $company_email = $yourCompany->email;
                $company_web = $yourCompany->web;
                $company_trn_no = $yourCompany->trn_no;
            }

            ?>
        </div>
        <div class='printAllTableForThisReport' style="width: 8.5in;">
            <table style="width: 100%; border-collapse: collapse; font-size: 11px;" class="item-list">
                <tr>
                    <td colspan="4"><img src="<?= Yii::app()->theme->baseUrl . "/images/logo.png" ?>"
                                         style="width: 100%; height: 100px;"></td>
                </tr>
                <tr>
                    <td colspan="2" style="border-right: white;">
                        <?php
                        echo "$company_road<br>";
                        echo "$company_house<br>";
                        echo "$company_location<br>";
                        echo "Ph : $company_contact<br>";
                        echo "Email: $company_email<br>";
                        echo "Website: $company_web<br>";
                        echo "TRN: $company_trn_no<br>";
                        ?>
                    </td>
                    <td colspan="2">
                        <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
                            <tr>
                                <td style="text-align: center;"><b>Challan No</b></td>
                                <td style="text-align: center;"><b>Date</b></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><?= reset($data)->challan_no ?></td>
                                <td style="text-align: center;"><?= date('d.m.Y', strtotime(reset($data)->date)) ?></td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tr>
                    <td style="text-align: center;">#</td>
                    <td style="text-align: center;">Description</td>
                    <td style="text-align: center; width: 15%;">Stock In</td>
                    <td style="text-align: center;  width: 15%;">Stock Out</td>
                </tr>
                <tbody>
                <?php
                $i = 1;
                foreach ($data as $dt) {
                    $unit_label = Units::model()->nameOfThis($dt->unit_id);
                    $unit_label_in = $unit_label_out = "";
                    if ($dt->stock_in > 0) {
                        $unit_label_in = $unit_label;
                    } else {
                        $unit_label_out = $unit_label;
                    }
                    ?>
                    <tr>
                        <td style="text-align: center;"><?= $i++ ?></td>
                        <td><?= $dt->model_name ?></td>
                        <td style="text-align: center;"><?= $dt->stock_in . " $unit_label_in" ?></td>
                        <td style="text-align: right;"><?= $dt->stock_out . " $unit_label_out" ?></td>
                    </tr>
                    <?php
                }
                ?>
                <tr>
                    <td colspan="6" style="height: 150px; vertical-align: bottom; text-align: left;">
                        <span style="text-decoration: overline;">Receivers Name, Signature & Mob No</span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <?php
        } else {
            ?>
            <div class="alert alert-danger" role="alert">
                No result found!
            </div>
            <?php
        }
        ?>
    </div>
</div>