<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>
    /* override styles when printing */
    @media print {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }

    @page {
        size: 8.27in 11.69in;  /* width height A4 size paper */
    }


    .item-list thead th,
    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
    }

    .heading td {
        min-height: 25px !important;
    }

    .heading tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }
</style>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Preview</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <!--            <button type="button" class="btn btn-tool" data-card-widget="remove">-->
            <!--                <i class="fa fa-times"></i>-->
            <!--            </button>-->
        </div>
    </div>
    <div class="card-body table-responsive">
        <div style="width: 100%">
            <?php
            if ($data) {
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => FALSE, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div>";

            ?>
        </div>
        <div class='printAllTableForThisReport ' style="width: 8.5in;">
            <table style="width: 100%; border-collapse: collapse; font-size: 11px;" class="item-list">
                <tr>
                    <td colspan="9" style="border: 1px solid white;">
                        <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
                            <tr>
                                <td style="text-align: center;"><b>Challan No</b></td>
                                <td style="text-align: center;"><b>Date</b></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><?= reset($data)->challan_no ?></td>
                                <td style="text-align: center;"><?= date('d.m.Y', strtotime(reset($data)->date)) ?></td>
                            </tr>
                        </table>
                        <div style="width: 100%; height: 20px;"></div>
                    </td>
                </tr>

                <tr>
                    <td style="text-align: center;">#</td>
                    <td style="text-align: center;">Description</td>
                    <td style="text-align: center;">Product SL No</td>
                    <td style="text-align: center; ">Stock In</td>
                    <td style="text-align: center;  ">Stock Out</td>
                    <td style="text-align: center;">P.P</td>
                    <td style="text-align: center;">S.P</td>
                    <td style="text-align: center;">T.P.P</td>
                    <td style="text-align: center;">T.S.P</td>
                </tr>
                <tbody>
                <?php
                $i = 1;
                $g_total_in_qty = $g_total_out_qty = $g_total_pp = $g_total_sp = 0;
                foreach ($data as $dt) {

                    $g_total_in_qty += $dt->stock_in;
                    $g_total_out_qty += $dt->stock_out;

                    $g_total_pp += $dt->purchase_price * ($g_total_in_qty > 0 ? $dt->stock_in : $dt->stock_out);
                    $g_total_sp += $dt->sell_price * ($g_total_out_qty > 0 ? $dt->stock_out : $dt->stock_in);
                    ?>
                    <tr>
                        <td style="text-align: center;"><?= $i++ ?></td>
                        <td style="text-align: left;"><?= $dt->model_name ?></td>
                        <td><?= $dt->product_sl_no ?></td>
                        <td style="text-align: center;"><?= $dt->stock_in ?></td>
                        <td style="text-align: center;"><?= $dt->stock_out ?></td>
                        <td><?= $dt->purchase_price ? number_format($dt->purchase_price, 2) : 0 ?></td>
                        <td><?= $dt->sell_price ? number_format($dt->sell_price, 2) : 0; ?></td>
                        <td><?= number_format($dt->purchase_price * ($dt->stock_in > 0 ? $dt->stock_in : $dt->stock_out), 2) ?></td>
                        <td><?= number_format($dt->sell_price * ($dt->stock_out > 0 ? $dt->stock_out : $dt->stock_in), 2) ?></td>
                    </tr>
                    <?php
                }
                ?>
                <tr>
                    <td colspan="3" style="text-align: right;"><b>Total</b></td>
                    <td style="text-align: center;"><b><?= $g_total_in_qty ?></b></td>
                    <td style="text-align: center;"><b><?= $g_total_out_qty ?></b></td>
                    <td></td>
                    <td></td>
                    <td style="text-align: right;"><b><?= number_format($g_total_pp, 2) ?></b></td>
                    <td style="text-align: right;"><b><?= number_format($g_total_sp, 2) ?></b></td>
                </tr>
                <tr>
                    <td colspan="6"
                        style="height: 150px; vertical-align: bottom; text-align: left; border: 1px solid white; background: white;">
                        <span style="text-decoration: overline;">Receivers Name, Signature & Mob No</span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <?php
        } else {
            ?>
            <div class="alert alert-danger" role="alert">
                No result found!
            </div>
            <?php
        }
        ?>
    </div>
</div>