<?php
/** @var SellOrder $data */
?>
<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>

    /* override styles when printing */
    @media print {
        body {
            margin: 0;
            padding: 0;
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        }

        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
            font-weight: bold;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }


    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
        font-family: fangsong;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }


    .top-sheet-item-list tbody th,
    .top-sheet-item-list tbody td,
    .top-sheet-footer td,
    .top-sheet-footer th {
        border: 1px solid black;
        font-family: fangsong;
    }

    .page-break-div {
        page-break-after: always !important;
    }

    .pageNumber::before {
        content: "Page " counter(page);
        position: absolute;
        bottom: 0;
        width: 100%;
        text-align: center;
    }
</style>

<div class="card card-primary  table-responsive">
    <div class="card-header">
        <h3 class="card-title">
            <?php
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => true, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div><br><br><br>";
            ?>
        </h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <div class="printAllTableForThisReport">
            <?php
            foreach ($data as $item) {
                if ($item) {
                    $customer = Customers::model()->findByPk($item->customer_id);
                    ?>
                    <div style="width: 100%; min-height: 80px;">
                    <h5>DELIVERY CHALLAN</h5>    
                        <?php
                            $this->renderPartial('application.modules.sell.views.sellOrder.without_pad_header');
                        ?>
                        <div style="width: 100%; float: left; clear: right; margin-bottom: 10px;">
                            <div style="width: 50%; float: left; clear: right;">
                                <h5>Customer Details</h5>
                                <?php
                                $customer_name = $customer_zip = $customer_city = $customer_state = $customer_phone = $customer_trn_no = "N/A";
                                if ($customer) {
                                    $customer_name = $customer->company_name;
                                    $customer_zip = $customer->zip;
                                    $customer_city = $customer->city;
                                    $customer_state = $customer->state;
                                    $customer_phone = $customer->owner_mobile_no;
                                    $customer_trn_no = $customer->trn_no;
                                }
                                echo "$customer_name<br>";
                                echo ($customer_zip || $customer_state) ? "$customer_zip, $customer_state<br>" : "";
                                echo ($customer_city) ? "$customer_city<br>" : "";
                                echo ($customer_phone) ? "$customer_phone<br>" : "";
                                echo ($customer_trn_no) ? "$customer_trn_no<br>" : "";
                                ?>
                            </div>
                            <div style="width: 50%; float: left; text-align: right; vertical-align: bottom;">
                            <b>Date:</b>
                                <?= date('d.m.Y', strtotime($item->date)) ?>
                                <br>

                                <b>Quotation No:</b>
                                <?= "$item->so_no" ?>
                            </div>
                        </div>
                    </div>
                    <table style="width: 100%; border-collapse: collapse; font-size: 12px;" class="item-list">
                        <thead>
                        <tr>
                            <td style="text-align: center; width: 2%; border: 1px solid black;">#</td>
                            <td style="text-align: center; border: 1px solid black;">Description</td>
                            <td style="text-align: center;  width: 10%; border: 1px solid black;">Qty</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $vat = $item->vat_amount;
                        $vat_percentage = $item->vat_percentage;
                        $delivery_charge = $item->delivery_charge;
                        $discount_amount = $item->discount_amount;
                        $criteria = new CDbCriteria();
                        $criteria->select = "pm.model_name, pm.code, pm.image, sum(t.qty) as qty, t.amount, t.discount_amount,
                                            t.note, sum(t.row_total) as row_total,  sum(costing) as costing,
                                            GROUP_CONCAT(product_sl_no ORDER BY product_sl_no SEPARATOR ', ') as product_sl_no, 
                                            GROUP_CONCAT(t.warranty ORDER BY t.warranty SEPARATOR ', ') as warranty,
                                            pm.description";
                        $criteria->join = " INNER JOIN prod_models pm on t.model_id = pm.id ";
                        $criteria->addColumnCondition(['t.sell_order_id' => $item->id]);
                        $criteria->group = "pm.id";
                        $criteria->order = "pm.item_id DESC, pm.model_name ASC";
                        $data2 = SellOrderDetails::model()->findAll($criteria);
                        $row_total = 0;
                        $totalCosting = 0;
                        if ($data2) {
                            $i = 1;
                            foreach ($data2 as $dt) {
                                ?>
                                <tr>
                                    <td style="text-align: center;"><?= $i++ ?></td>
                                    <td>
                                        <?= $dt->model_name ?>
                                        <?php
                                        if ($dt->note) {
                                            echo "<br>" . nl2br($dt->note);
                                        }
                                        if (isset($dt->product_sl_no) && strlen($dt->product_sl_no) > 0) {
                                            echo "<br><b>SL:</b>$dt->product_sl_no";
                                        }

                                        if (strlen((string)$dt->warranty) > 0) {
                                            $dataArrayWarranty = explode(', ', $dt->warranty);
                                            $dataArrayWarrantyUnique = array_unique($dataArrayWarranty);
                                            $dataArrayWarrantyUnique = array_values($dataArrayWarrantyUnique);

                                            $warranty = implode(', ', $dataArrayWarrantyUnique);
                                            echo "<br><b>Warranty: </b> <i>$warranty Month</i>";
                                        }
                                        ?>
                                    </td>
                                    <td style="text-align: center;"><?= number_format($dt->qty) ?></td>
                                </tr>
                                <?php
                                $row_total += $dt->row_total;
                                $totalCosting += ($dt->costing);
                            }
                            if ($totalCosting != $item->costing) {
                                $item->costing = $totalCosting;
                                $item->save();
                            }
                        } else {
                            ?>
                            <tr>
                                <td colspan="6">
                                    <div class="alert alert-danger" role="alert">
                                        No item found
                                    </div>
                                </td>
                            </tr>
                            <?php
                        }
                        $actualGrandTotal = ROUND((($row_total + $vat + $delivery_charge) - $discount_amount), 2);
                        if ($actualGrandTotal != $item->grand_total) {
                            $item->grand_total = $actualGrandTotal;
                            $item->total_due = $actualGrandTotal;
                            $item->save();
                        }
                        ?>
                        </tbody>
                    </table>

                    <div style="width: 100%; float: left; clear: right; height: 150px; font-size: 12px; margin-top: 20px;">
                        <div style="height: 30px; text-align: left; width: 100%; float: left; clear: right;">
                            By signing this document, the customer agrees to he services and conditions
                            described in this document.
                        </div>
                        <br>
                        <div style="width: 100%; float: left; clear:right;">

                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <span style="text-decoration: underline; font-weight: bold;">The Mihan Engineers (TMEBD)</span>
                            </div>
                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <span style="text-decoration: underline; font-weight: bold;"><?= $customer_name ?></span>
                            </div>
                        </div>
                        <div style="height: 50px; width: 100%; float: left; clear: right; margin-top: 40px;">
                            <div style="width: 50%; float: left; clear: right; margin: auto; display: flex; flex-direction: column; justify-content: center; align-items: center;">
                                <div style="font-weight: bold; text-transform: uppercase;">
                                    <?= User::model()->nameOfThis($item->created_by) ?>
                                </div>
                                <div style="text-decoration: overline;"><?= date('F d, Y') ?></div>
                            </div>

                            <div style="width: 50%; float: left;clear:right; text-decoration: overline; margin: auto; display: flex;  justify-content: center;  align-items: center;">
                                <div>(&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    )
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="page-break-div"></div>
                <?php
                } else {
                ?>
                    <div class="alert alert-danger" role="alert">
                        No result found!
                    </div>
                    <?php
                }
            }
            ?>

        </div>
    </div>
</div>