<?php
/** @var SellOrder $data */
?>
<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>

    /* override styles when printing */
    @media print {
        /* Set A4 paper size and minimum margins */
        @page {
            size: A4;
            margin: 8mm 5mm 15mm 5mm; /* bottom space for footer */
        }
        body {
            margin: 0;
            padding: 0;
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        }

        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
            font-weight: bold;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }


    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
        font-family: fangsong;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }


    .top-sheet-item-list tbody th,
    .top-sheet-item-list tbody td,
    .top-sheet-footer td,
    .top-sheet-footer th {
        border: 1px solid black;
        font-family: fangsong;
    }

    .page-break-div {
        page-break-after: always !important;
    }

    .pageNumber::before {
        content: "Page " counter(page);
        position: absolute;
        bottom: 0;
        width: 100%;
        text-align: center;
    }
</style>

<div class="card card-primary  table-responsive">
    <div class="card-header">
        <h3 class="card-title">
            <?php
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                    'title' => ' ', //the title of the document. Defaults to the HTML title
                    'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                    'text' => '', //text which will appear beside the print icon. Defaults to NULL
                    'element' => '.printAllTableForThisReport', //the element to be printed.
                    'exceptions' => array(//the element/s which will be ignored
                            '.summary',
                            '.search-form',
                            '#excludeDiv',
                    ),
                    'publishCss' => FALSE, //publish the CSS for the whole page?
                    'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                    'alt' => 'print', //text which will appear if image can't be loaded
                    'debug' => true, //enable the debugger to see what you will get
                    'id' => 'print-div'         //id of the print link
            ));
            echo "</div><br><br><br>";
            ?>
        </h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <div class="printAllTableForThisReport">
            <?php
            foreach ($data as $item) {
                if ($item) {
                    $customer = Customers::model()->findByPk($item->customer_id);
                    ?>
                    <div style="width: 100%; min-height: 80px;">
                        <?php
                        if (isset($preview_type)) {
                            if ($preview_type == SellOrder::NORMAL_PAD_PRINT) {
                                $this->renderPartial('application.modules.sell.views.sellOrderQuotation.pad_header');
                            } else {
                                $this->renderPartial('application.modules.sell.views.sellOrderQuotation.without_pad_header');
                            }
                        } else {
                            $this->renderPartial('application.modules.sell.views.sellOrderQuotation.without_pad_header');
                        }
                        ?>
                        <div style="width: 100%; float: left; clear: right; margin-bottom: 10px;">
                            <div style="width: 25%; float: left; clear: right; text-align: left;">
                                <?php
                                $customer_name = $customer_zip = $customer_city = $customer_state = $customer_phone = $customer_trn_no = "N/A";
                                if ($customer) {
                                    $customer_name = $customer->company_name;
                                    $customer_zip = $customer->zip;
                                    $customer_city = $customer->city;
                                    $customer_state = $customer->state;
                                    $customer_phone = $customer->owner_mobile_no;
                                    $customer_trn_no = $customer->trn_no;
                                }
                                echo "$customer_name<br>";
                                ?>
                            </div>
                            <div style="width: 33%; float: left; text-align: center; vertical-align: bottom; ">
                                <b>Draft No:</b>
                                <?= "$item->so_no" ?>
                                <br>
                            </div>
                            <div style="width: 33%; float: left; text-align: right; vertical-align: bottom; ">
                                <b>Date:</b>
                                <?= date('d.m.Y', strtotime($item->date)) ?>
                                <br>

                            </div>
                        </div>
                    </div>
                    <table style="width: 100%; border-collapse: collapse; font-size: 12px;" class="item-list">
                        <thead>
                        <tr>
                            <td style="text-align: center; width: 2%; border: 1px solid black;">#</td>
                            <td style="text-align: center; border: 1px solid black;">Description</td>
                            <td style="text-align: center;  width: 10%; border: 1px solid black;">Qty</td>
                            <td style="text-align: center;  width: 10%; border: 1px solid black;">Return Qty</td>
                            <td style="text-align: center;  width: 10%; border: 1px solid black;">Unit Price</td>
                            <td style="text-align: center;  width: 10%; border: 1px solid black;">Sold Qty</td>
                            <td style="text-align: center; width: 10%; border: 1px solid black;">Total</td>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $vat = $item->vat_amount;
                        $vat_percentage = $item->vat_percentage;
                        $delivery_charge = $item->delivery_charge;
                        $discount_amount = $item->discount_amount;
                        $criteria = new CDbCriteria();
                        $criteria->select = "pm.model_name, pm.code, pm.image, sum(t.qty) as qty, t.amount, t.discount_amount,
                                            t.note, sum(t.row_total) as row_total,  sum(costing) as costing,
                                            companies.name as company_name,
                                            pm.description";
                        $criteria->join = " INNER JOIN prod_models pm on t.model_id = pm.id ";
                        $criteria->join .= " INNER JOIN companies on pm.manufacturer_id = companies.id ";
                        $criteria->addColumnCondition(['t.sell_order_id' => $item->id]);
                        $criteria->group = "pm.id";
                        $criteria->order = "companies.name, pm.item_id DESC, pm.model_name ASC";
                        $data2 = SellOrderQuotationDetails::model()->findAll($criteria);
                        $row_total = 0;
                        $totalCosting = 0;
                        if ($data2) {
                            $i = 1;

                            $lastCompany = '';

                            foreach ($data2 as $dt) {
                                if (!$dt->qty > 0) {
                                    continue;
                                }
                                // 👉 Print company name once
                                if ($lastCompany !== $dt->company_name) {
                                    $lastCompany = $dt->company_name;
                                    ?>
                                    <tr>
                                        <td colspan="7"
                                            style="background:#f4f6f9;font-weight:600;padding:8px 10px; text-align: left;">
                                            <?= CHtml::encode($dt->company_name) ?>
                                        </td>
                                    </tr>
                                    <?php
                                }
                                ?>
                                <tr>
                                    <td style="text-align: center;"><?= $i++ ?></td>
                                    <td style="text-align: left;">
                                        <?= $dt->model_name ?>
                                    </td>
                                    <td style="text-align: center;"><?= number_format($dt->qty) ?></td>
                                    <td style="text-align: right;"></td>
                                    <td style="text-align: right;"></td>
                                    <td style="text-align: right;"></td>
                                    <td style="text-align: right;"></td>
                                </tr>
                                <?php
                                $row_total += $dt->row_total;
                            }
                        } else {
                            ?>
                            <tr>
                                <td colspan="6">
                                    <div class="alert alert-danger" role="alert">
                                        No item found
                                    </div>
                                </td>
                            </tr>
                            <?php
                        }
                        $actualGrandTotal = ROUND((($row_total + $vat + $delivery_charge) - $discount_amount), 2);
                        if ($actualGrandTotal != $item->grand_total) {
                            $item->grand_total = $actualGrandTotal;
                            $item->total_due = $actualGrandTotal;
                            $item->save();
                        }
                        ?>
                        <tr>
                            <td rowspan="8" colspan="4"
                                style="border: none; background: white; text-align: left; letter-spacing: 1px; font-weight: bold;">
                            </td>
                            <td colspan="2" style=" background: white; text-align: left; border-right: none;">Sub Total</td>
                            <td style="text-align: right; border-left: none; "></td>
                        </tr>
                        <tr>
                            <td colspan="2" style=" background: white; text-align: left; border-right: none;">Vat (+)
                            </td>
                            <td style="text-align: right; border-left: none; "></td>
                        </tr>
                        <tr>
                            <td colspan="2" style=" background: white; text-align: left; border-right: none;">Delivery Charge (+)</td>
                            <td style="text-align: right; border-left: none; "></td>
                        </tr>
                        <tr>
                            <td colspan="2" style=" background: white; text-align: left; border-right: none;">S.R Commission (-)</td>
                            <td style="text-align: right; border-left: none; ">
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" style=" background: white; text-align: left; border-right: none;">Discount (-)</td>
                            <td style="text-align: right; border-left: none; ">
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" style=" background: white; text-align: left; border-right: none;">Damage (-)</td>
                            <td style="text-align: right; border-left: none; ">
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2" style=" background: white; text-align: left; border-right: none;">Road Charge (-)</td>
                            <td style="text-align: right; border-left: none; ">
                            </td>
                        </tr>
                        <tr style="font-weight: bold;">
                            <td colspan="2" style=" background: white; text-align: left; border-right: none;">
                                Net payable amount
                            </td>
                            <td style="text-align: right; border-left: none; ">
                            </td>
                        </tr>
                        </tbody>
                    </table>

                    <div class="page-break-div"></div>
                    <?php
                } else {
                    ?>
                    <div class="alert alert-danger" role="alert">
                        No result found!
                    </div>
                    <?php
                }
            }
            ?>

        </div>
    </div>
</div>