<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>
    /* override styles when printing */
    @media print {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }

    @page {
        size: 8.27in 11.69in;  /* width height A4 size paper */
    }


    .item-list thead th,
    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
    }

    .heading td {
        min-height: 25px !important;
    }

    .heading tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }
</style>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Preview</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <!--            <button type="button" class="btn btn-tool" data-card-widget="remove">-->
            <!--                <i class="fa fa-times"></i>-->
            <!--            </button>-->
        </div>
    </div>
    <div class="card-body table-responsive">
        <div style="width: 100%">
            <?php
            if ($data) {
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => FALSE, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div>";
            $yourCompany = YourCompany::model()->findByAttributes(['is_active' => YourCompany::ACTIVE]);
            $company_name = $company_location = $company_road = $company_house = $company_contact = $company_email = $company_web = $company_trn_no = "N/A";
            if ($yourCompany) {
                $company_name = $yourCompany->company_name;
                $company_location = $yourCompany->location;
                $company_road = $yourCompany->road;
                $company_house = $yourCompany->house;
                $company_contact = $yourCompany->contact;
                $company_email = $yourCompany->email;
                $company_web = $yourCompany->web;
                $company_trn_no = $yourCompany->trn_no;
            }
            ?>
        </div>
        <div class='printAllTableForThisReport' style="width: 95%;">
            <table style="width: 100%; border-collapse: collapse; font-size: 11px;" class="item-list">
                <tr>
                    <td colspan="4" style="vertical-align: middle; border: 1px solid white;">
                        <div style="width: 70%; float: left;">
<!--                            <img src="--><?php //= Yii::app()->theme->baseUrl . "/images/logo.png" ?><!--"-->
<!--                                 style="width: 130px; height: 100px;">-->
                        </div>
                        <div style="width: 29%; float: right; vertical-align: middle; text-align: center;">
                            <h5 style="vertical-align: middle; border: 1px dotted black; padding: 5px;">EXPENSE VOUCHER</h5>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="4" style=" border: 1px solid white;">
                        <table style="width: 100%; border-collapse: collapse; font-size: 11px; border: 1px solid white;">
                            <tr>
                                <td style="text-align: center;"><b>Date</b></td>
                                <td style="text-align: center;"><?= date('d.m.Y', strtotime($data->date)) ?></td>
                                <td style="text-align: center;"><b>Entry No</b></td>
                                <td style="text-align: center;"><?= "$data->entry_no" ?></td>
                                <td style="text-align: center;"><b>Created By</b></td>
                                <td style="text-align: center;"><?= Users::model()->nameOfThis($data->created_by) ?></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: center;">#</td>
                    <td style="text-align: center;">Description</td>
                    <td style="text-align: center;">Note</td>
                    <td style="text-align: center;">Amount</td>
                </tr>
                <tbody>
                <?php
                $criteria = new CDbCriteria();
                $criteria->select = "t.*, eh.title";
                $criteria->join = " INNER JOIN expense_head eh on t.expense_head_id = eh.id ";
                $criteria->addColumnCondition(['t.expense_id' => $data->id]);
                $criteria->order = "eh.title ASC";
                $data3 = ExpenseDetails::model()->findAll($criteria);
                $grand_total = 0;
                if ($data3) {
                    $i = 1;
                    foreach ($data3 as $dt) {
                        $grand_total += $dt->amount;
                        ?>
                        <tr>
                            <td style="text-align: center;"><?= $i++ ?></td>
                            <td><?= $dt->title ?></td>
                            <td style="text-align: center;"><?= $dt->remarks ?></td>
                            <td style="text-align: right;"><?= $dt->amount ?></td>
                        </tr>
                        <?php
                    }
                } else {
                    ?>
                    <tr>
                        <td colspan="4">
                            <div class="alert alert-danger" role="alert">
                                No item found
                            </div>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                <tr>
                    <td colspan="3" style="text-align: right;">Total</td>
                    <td style="text-align: right;"> <?= $grand_total ?></td>
                </tr>
                <tr>
                    <td colspan="4" style="height: 150px; vertical-align: bottom; text-align: left; border: 1px solid white; background: white;">
                        <span style="text-decoration: overline;">Receivers Name, Signature & Mob No</span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <?php
        } else {
            ?>
            <div class="alert alert-danger" role="alert">
                No result found!
            </div>
            <?php
        }
        ?>
    </div>
</div>