<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>
    /* override styles when printing */
    @media print {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }

    @page {
        size: 8.27in 11.69in;  /* width height A4 size paper */
    }


    .item-list thead th,
    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
    }

    .heading td {
        min-height: 25px !important;
    }

    .heading tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }
</style>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Preview</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <!--            <button type="button" class="btn btn-tool" data-card-widget="remove">-->
            <!--                <i class="fa fa-times"></i>-->
            <!--            </button>-->
        </div>
    </div>
    <div class="card-body">
        <div style="width: 100%">
            <?php
            if ($data) {
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => FALSE, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div>";
            $yourCompany = YourCompany::model()->findByAttributes(['is_active' => YourCompany::ACTIVE]);
            $company_name = $company_location = $company_road = $company_house = $company_contact = $company_email = $company_web = $company_trn_no = "N/A";
            if ($yourCompany) {
                $company_name = $yourCompany->company_name;
                $company_location = $yourCompany->location;
                $company_road = $yourCompany->road;
                $company_house = $yourCompany->house;
                $company_contact = $yourCompany->contact;
                $company_email = $yourCompany->email;
                $company_web = $yourCompany->web;
                $company_trn_no = $yourCompany->trn_no;
            }
            $order = SellOrder::model()->findByPk($data->order_id);
            $customer = Customers::model()->findByPk($order->customer_id);
            ?>
        </div>
        <div class='printAllTableForThisReport' style="width: 8.5in;">
            <table style="width: 100%; border-collapse: collapse; font-size: 11px;" class="item-list">
                <tr>
                    <td colspan="3" style="vertical-align: middle;">
                        <div style="width: 70%; float: left;">
                            <img src="<?= Yii::app()->theme->baseUrl . "/images/logo.png" ?>"
                                 style="width: 100%; height: 100px;">
                        </div>
                        <div style="width: 29%; float: right; vertical-align: middle; text-align: center;">
                            <h3 style="vertical-align: middle;">PRODUCTION</h3>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td colspan="3" style="border-right: white;">
                        <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
                            <tr>
                                <td style="text-align: center;"><b>Production No</b></td>
                                <td style="text-align: center;"><?= "$data->production_no" ?></td>
                                <td style="text-align: center;"><b>Issue Date</b></td>
                                <td style="text-align: center;"><?= date('d.m.Y', strtotime($data->date)) ?></td>
                                <td style="text-align: center;"><b>Issue By</b></td>
                                <td style="text-align: center;"><?= Users::model()->nameOfThis($order->created_by) ?></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><b>Order No</b></td>
                                <td style="text-align: center;"><?= "$order->so_no" ?></td>
                                <td style="text-align: center;"><b>Order Date</b></td>
                                <td style="text-align: center;"><?= date('d.m.Y', strtotime($order->date)) ?></td>
                                <td style="text-align: center;"><b>Job Card No</b></td>
                                <td style="text-align: center;"><?= "$order->job_no" ?></td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tbody>
                <tr>
                    <td colspan="3" style="height: 30px;"></td>
                </tr>
                <tr>
                    <td style="text-align: center; width: 60px;">#</td>
                    <td style="text-align: center;">Materials</td>
                    <td style="text-align: center; width: 20%;">Production Qty</td>
                </tr>
                <?php
                $criteria = new CDbCriteria();
                $criteria->select = "t.*, pm.model_name, pm.code, pm.image";
                $criteria->join = " INNER JOIN prod_models pm on t.model_id = pm.id ";
                $criteria->addColumnCondition(['t.production_id' => $data->id]);
                $criteria->order = "pm.model_name ASC";
                $data2 = ProductionDetails::model()->findAll($criteria);
                $row_total = 0;
                if ($data2) {
                    $i = 1;
                    foreach ($data2 as $dt) {
                        ?>
                        <tr>
                            <td style="text-align: center;"><?= $i++ ?></td>
                            <td><?= $dt->model_name ?></td>
                            <td style="text-align: center;"><?= $dt->qty ?></td>
                        </tr>
                        <?php
                    }
                } else {
                    ?>
                    <tr>
                        <td colspan="3">
                            <div class="alert alert-danger" role="alert">
                                No item found
                            </div>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
            </table>
        </div>
        <?php
        } else {
            ?>
            <div class="alert alert-danger" role="alert">
                No result found!
            </div>
            <?php
        }
        ?>
    </div>
</div>