<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>

    /* override styles when printing */
    @media print {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }

    @page {
        size: 8.27in 11.69in;  /* width height A4 size paper */
    }


    .item-list thead th,
    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
    }

    .heading td {
        min-height: 25px !important;
    }

    .heading tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }
</style>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Preview</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <!--            <button type="button" class="btn btn-tool" data-card-widget="remove">-->
            <!--                <i class="fa fa-times"></i>-->
            <!--            </button>-->
        </div>
    </div>
    <div class="card-body">
        <div style="width: 100%">
            <?php
            if ($data) {
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => FALSE, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div>";
            $yourCompany = YourCompany::model()->findByAttributes(['is_active' => YourCompany::ACTIVE]);
            $company_name = $company_location = $company_road = $company_house = $company_contact = $company_email = $company_web = $company_trn_no = "N/A";
            if ($yourCompany) {
                $company_name = $yourCompany->company_name;
                $company_location = $yourCompany->location;
                $company_road = $yourCompany->road;
                $company_house = $yourCompany->house;
                $company_contact = $yourCompany->contact;
                $company_email = $yourCompany->email;
                $company_web = $yourCompany->web;
                $company_trn_no = $yourCompany->trn_no;
            }

            $customer = Customers::model()->findByPk($data->customer_id);
            $order = SellOrder::model()->findByPk($data->order_id);
            ?>
        </div>
        <div class='printAllTableForThisReport' style="width: 8.5in;">
            <table style="width: 100%; border-collapse: collapse; font-size: 11px;" class="item-list">
                <tr>
                    <td colspan="4"><img src="<?= Yii::app()->theme->baseUrl . "/images/logo.png" ?>"
                                         style="width: 100%; height: 100px;"></td>
                    <td style="text-align: center;" colspan="2"><h3>TAX INVOICE</h3></td>
                </tr>
                <tr>
                    <td colspan="3" style="border-right: white;">
                        <?php
                        echo "$company_road<br>";
                        echo "$company_house<br>";
                        echo "$company_location<br>";
                        echo "Ph : $company_contact<br>";
                        echo "Email: $company_email<br>";
                        echo "Website: $company_web<br>";
                        echo "TRN: $company_trn_no<br>";
                        ?>
                    </td>
                    <td colspan="3">
                        <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
                            <tr>
                                <td style="text-align: center;"><b>Invoice No</b></td>
                                <td style="text-align: center;"><b>Date</b></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><?= "$data->invoice_no" ?></td>
                                <td style="text-align: center;"><?= date('d.m.Y', strtotime($data->date)) ?></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><b>Order No</b></td>
                                <td style="text-align: center;"><b>Date</b></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><?= "$order->so_no" ?></td>
                                <td style="text-align: center;"><?= date('d.m.Y', strtotime($order->date)) ?></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><b>Customer Code</b></td>
                                <td style="text-align: center;"><b>LPO No</b></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><?= $customer->customer_code ?></td>
                                <td style="text-align: center;"></td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td colspan="6">
                        <h5>Customer Details</h5>
                        <?php
                        $customer_name = $customer_zip = $customer_city = $customer_state = $customer_phone = $customer_trn_no = "N/A";
                        if ($customer) {
                            $customer_name = $customer->company_name;
                            $customer_zip = $customer->zip;
                            $customer_city = $customer->city;
                            $customer_state = $customer->state;
                            $customer_phone = $customer->owner_mobile_no;
                            $customer_trn_no = $customer->trn_no;
                        }
                        echo "$customer_name<br>";
                        echo "$customer_zip, $customer_state<br>";
                        echo "$customer_city<br>";
                        echo "$customer_phone<br>";
                        echo "$customer_trn_no<br>";
                        ?>
                    </td>
                </tr>
                <tr>
                    <td style="text-align: center;">#</td>
                    <td style="text-align: center;">Description</td>
                    <td style="text-align: center;">Color</td>
                    <td style="text-align: center;  width: 10%;">Qty</td>
                    <td style="text-align: center;  width: 10%;">Price</td>
                    <td style="text-align: center; width: 10%;">Total</td>
                </tr>
                <tbody>
                <?php
                $vat = $data->vat_amount;
                $criteria = new CDbCriteria();
                $criteria->select = "t.*, pm.model_name, pm.code, pm.image, pm.unit_id";
                $criteria->join = " INNER JOIN prod_models pm on t.model_id = pm.id ";
                $criteria->addColumnCondition(['t.invoice_id' => $data->id]);
                $criteria->order = "pm.model_name ASC";
                $data2 = InvoiceDetails::model()->findAll($criteria);
                $row_total = 0;
                if ($data2) {
                    $i = 1;
                    foreach ($data2 as $dt) {
                        ?>
                        <tr>
                            <td style="text-align: center;"><?= $i++ ?></td>
                            <td><?= $dt->model_name ?></td>
                            <td><?= $dt->color ?></td>
                            <td style="text-align: center;"><?= $dt->qty ?></td>
                            <td style="text-align: right;"><?= $dt->unit_price ?></td>
                            <td style="text-align: right;"><?= $dt->row_total ?></td>
                        </tr>
                        <?php
                        $row_total += $dt->row_total;
                    }
                } else {
                    ?>
                    <tr>
                        <td colspan="6">
                            <div class="alert alert-danger" role="alert">
                                No item found
                            </div>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                <tr>
                    <td rowspan="3" colspan="3">
                        <div>Total Amount In Words:</div>
                        <div>Dirhams:
                            <?php
                            $amountInWord = new AmountInWord();
                            $inword = $amountInWord->convert(intval($row_total));
                            if ($amountInWord->convertFloat($row_total)) {
                                $inword .= $amountInWord->convertFloat($row_total) . ' Only';
                            } else {
                                $inword .= ' Only';
                            }
                            echo $inword;
                            ?>
                        </div>
                    </td>
                    <td colspan="2">Sub Total</td>
                    <td style="text-align: right;"><?= $row_total ?></td>
                </tr>
                <tr>
                    <td colspan="2">Vat</td>
                    <td style="text-align: right;"><?= $vat ?></td>
                </tr>
                <tr>
                    <td colspan="2">Grand Total</td>
                    <td style="text-align: right;"><?= $data->grand_total ?></td>
                </tr>
                <tr>
                    <td colspan="6" style="height: 150px; vertical-align: bottom; text-align: left;">
                        <span style="text-decoration: overline;">Receivers Name, Signature & Mob No</span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <?php
        } else {
            ?>
            <div class="alert alert-danger" role="alert">
                No result found!
            </div>
            <?php
        }
        ?>
    </div>
</div>