INSERT INTO countries (id, iso2, iso3, country) VALUES (1, 'AF', 'AFG', 'Afghanistan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (2, 'AX', 'ALA', 'Åland Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (4, 'DZ', 'DZA', 'Algeria (El Djazaïr)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (3, 'AL', 'ALB', 'Albania');
INSERT INTO countries (id, iso2, iso3, country) VALUES (5, 'AS', 'ASM', 'American Samoa');
INSERT INTO countries (id, iso2, iso3, country) VALUES (6, 'AD', 'AND', 'Andorra');
INSERT INTO countries (id, iso2, iso3, country) VALUES (7, 'AO', 'AGO', 'Angola');
INSERT INTO countries (id, iso2, iso3, country) VALUES (8, 'AI', 'AIA', 'Anguilla');
INSERT INTO countries (id, iso2, iso3, country) VALUES (9, 'AQ', 'ATA', 'Antarctica');
INSERT INTO countries (id, iso2, iso3, country) VALUES (10, 'AG', 'ATG', 'Antigua and Barbuda');
INSERT INTO countries (id, iso2, iso3, country) VALUES (11, 'AR', 'ARG', 'Argentina');
INSERT INTO countries (id, iso2, iso3, country) VALUES (12, 'AM', 'ARM', 'Armenia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (13, 'AW', 'ABW', 'Aruba');
INSERT INTO countries (id, iso2, iso3, country) VALUES (14, 'AU', 'AUS', 'Australia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (15, 'AT', 'AUT', 'Austria');
INSERT INTO countries (id, iso2, iso3, country) VALUES (16, 'AZ', 'AZE', 'Azerbaijan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (17, 'BS', 'BHS', 'Bahamas');
INSERT INTO countries (id, iso2, iso3, country) VALUES (18, 'BH', 'BHR', 'Bahrain');
INSERT INTO countries (id, iso2, iso3, country) VALUES (19, 'BD', 'BGD', 'Bangladesh');
INSERT INTO countries (id, iso2, iso3, country) VALUES (20, 'BB', 'BRB', 'Barbados');
INSERT INTO countries (id, iso2, iso3, country) VALUES (21, 'BY', 'BLR', 'Belarus');
INSERT INTO countries (id, iso2, iso3, country) VALUES (22, 'BE', 'BEL', 'Belgium');
INSERT INTO countries (id, iso2, iso3, country) VALUES (23, 'BZ', 'BLZ', 'Belize');
INSERT INTO countries (id, iso2, iso3, country) VALUES (24, 'BJ', 'BEN', 'Benin');
INSERT INTO countries (id, iso2, iso3, country) VALUES (25, 'BM', 'BMU', 'Bermuda');
INSERT INTO countries (id, iso2, iso3, country) VALUES (26, 'BT', 'BTN', 'Bhutan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (27, 'BO', 'BOL', 'Bolivia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (28, 'BA', 'BIH', 'Bosnia and Herzegovina');
INSERT INTO countries (id, iso2, iso3, country) VALUES (29, 'BW', 'BWA', 'Botswana');
INSERT INTO countries (id, iso2, iso3, country) VALUES (30, 'BV', 'BVT', 'Bouvet Island');
INSERT INTO countries (id, iso2, iso3, country) VALUES (31, 'BR', 'BRA', 'Brazil');
INSERT INTO countries (id, iso2, iso3, country) VALUES (32, 'IO', 'IOT', 'British Indian Ocean Territory');
INSERT INTO countries (id, iso2, iso3, country) VALUES (33, 'BN', 'BRN', 'Brunei Darussalam');
INSERT INTO countries (id, iso2, iso3, country) VALUES (34, 'BG', 'BGR', 'Bulgaria');
INSERT INTO countries (id, iso2, iso3, country) VALUES (35, 'BF', 'BFA', 'Burkina Faso');
INSERT INTO countries (id, iso2, iso3, country) VALUES (36, 'BI', 'BDI', 'Burundi');
INSERT INTO countries (id, iso2, iso3, country) VALUES (37, 'KH', 'KHM', 'Cambodia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (38, 'CM', 'CMR', 'Cameroon');
INSERT INTO countries (id, iso2, iso3, country) VALUES (39, 'CA', 'CAN', 'Canada');
INSERT INTO countries (id, iso2, iso3, country) VALUES (40, 'CV', 'CPV', 'Cape Verde');
INSERT INTO countries (id, iso2, iso3, country) VALUES (41, 'KY', 'CYM', 'Cayman Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (42, 'CF', 'CAF', 'Central African Republic');
INSERT INTO countries (id, iso2, iso3, country) VALUES (43, 'TD', 'TCD', 'Chad (T''Chad)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (44, 'CL', 'CHL', 'Chile');
INSERT INTO countries (id, iso2, iso3, country) VALUES (45, 'CN', 'CHN', 'China');
INSERT INTO countries (id, iso2, iso3, country) VALUES (46, 'CX', 'CXR', 'Christmas Island');
INSERT INTO countries (id, iso2, iso3, country) VALUES (47, 'CC', 'CCK', 'Cocos (Keeling) Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (48, 'CO', 'COL', 'Colombia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (49, 'KM', 'COM', 'Comoros');
INSERT INTO countries (id, iso2, iso3, country) VALUES (50, 'CG', 'COG', 'Congo, Republic Of');
INSERT INTO countries (id, iso2, iso3, country) VALUES (51, 'CD', 'COD', 'Congo, The Democratic Republic of the (formerly Zaire)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (52, 'CK', 'COK', 'Cook Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (53, 'CR', 'CRI', 'Costa Rica');
INSERT INTO countries (id, iso2, iso3, country) VALUES (54, 'CI', 'CIV', 'CÔte D''Ivoire (Ivory Coast)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (55, 'HR', 'HRV', 'Croatia (hrvatska)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (56, 'CU', 'CUB', 'Cuba');
INSERT INTO countries (id, iso2, iso3, country) VALUES (57, 'CY', 'CYP', 'Cyprus');
INSERT INTO countries (id, iso2, iso3, country) VALUES (58, 'CZ', 'CZE', 'Czech Republic');
INSERT INTO countries (id, iso2, iso3, country) VALUES (59, 'DK', 'DNK', 'Denmark');
INSERT INTO countries (id, iso2, iso3, country) VALUES (60, 'DJ', 'DJI', 'Djibouti');
INSERT INTO countries (id, iso2, iso3, country) VALUES (61, 'DM', 'DMA', 'Dominica');
INSERT INTO countries (id, iso2, iso3, country) VALUES (62, 'DO', 'DOM', 'Dominican Republic');
INSERT INTO countries (id, iso2, iso3, country) VALUES (63, 'EC', 'ECU', 'Ecuador');
INSERT INTO countries (id, iso2, iso3, country) VALUES (64, 'EG', 'EGY', 'Egypt');
INSERT INTO countries (id, iso2, iso3, country) VALUES (65, 'SV', 'SLV', 'El Salvador');
INSERT INTO countries (id, iso2, iso3, country) VALUES (66, 'GQ', 'GNQ', 'Equatorial Guinea');
INSERT INTO countries (id, iso2, iso3, country) VALUES (67, 'ER', 'ERI', 'Eritrea');
INSERT INTO countries (id, iso2, iso3, country) VALUES (68, 'EE', 'EST', 'Estonia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (69, 'ET', 'ETH', 'Ethiopia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (70, 'FO', 'FRO', 'Faeroe Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (71, 'FK', 'FLK', 'Falkland Islands (Malvinas)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (72, 'FJ', 'FJI', 'Fiji');
INSERT INTO countries (id, iso2, iso3, country) VALUES (73, 'FI', 'FIN', 'Finland');
INSERT INTO countries (id, iso2, iso3, country) VALUES (74, 'FR', 'FRA', 'France');
INSERT INTO countries (id, iso2, iso3, country) VALUES (75, 'GF', 'GUF', 'French Guiana');
INSERT INTO countries (id, iso2, iso3, country) VALUES (76, 'PF', 'PYF', 'French Polynesia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (77, 'TF', 'ATF', 'French Southern Territories');
INSERT INTO countries (id, iso2, iso3, country) VALUES (78, 'GA', 'GAB', 'Gabon');
INSERT INTO countries (id, iso2, iso3, country) VALUES (79, 'GM', 'GMB', 'Gambia, The');
INSERT INTO countries (id, iso2, iso3, country) VALUES (80, 'GE', 'GEO', 'Georgia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (81, 'DE', 'DEU', 'Germany (Deutschland)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (82, 'GH', 'GHA', 'Ghana');
INSERT INTO countries (id, iso2, iso3, country) VALUES (83, 'GI', 'GIB', 'Gibraltar');
INSERT INTO countries (id, iso2, iso3, country) VALUES (84, 'GB', 'GBR', 'Great Britain');
INSERT INTO countries (id, iso2, iso3, country) VALUES (85, 'GR', 'GRC', 'Greece');
INSERT INTO countries (id, iso2, iso3, country) VALUES (86, 'GL', 'GRL', 'Greenland');
INSERT INTO countries (id, iso2, iso3, country) VALUES (87, 'GD', 'GRD', 'Grenada');
INSERT INTO countries (id, iso2, iso3, country) VALUES (88, 'GP', 'GLP', 'Guadeloupe');
INSERT INTO countries (id, iso2, iso3, country) VALUES (89, 'GU', 'GUM', 'Guam');
INSERT INTO countries (id, iso2, iso3, country) VALUES (90, 'GT', 'GTM', 'Guatemala');
INSERT INTO countries (id, iso2, iso3, country) VALUES (91, 'GN', 'GIN', 'Guinea');
INSERT INTO countries (id, iso2, iso3, country) VALUES (92, 'GW', 'GNB', 'Guinea-bissau');
INSERT INTO countries (id, iso2, iso3, country) VALUES (93, 'GY', 'GUY', 'Guyana');
INSERT INTO countries (id, iso2, iso3, country) VALUES (94, 'HT', 'HTI', 'Haiti');
INSERT INTO countries (id, iso2, iso3, country) VALUES (95, 'HM', 'HMD', 'Heard Island and Mcdonald Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (96, 'HN', 'HND', 'Honduras');
INSERT INTO countries (id, iso2, iso3, country) VALUES (97, 'HK', 'HKG', 'Hong Kong (Special Administrative Region of China)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (98, 'HU', 'HUN', 'Hungary');
INSERT INTO countries (id, iso2, iso3, country) VALUES (99, 'IS', 'ISL', 'Iceland');
INSERT INTO countries (id, iso2, iso3, country) VALUES (100, 'IN', 'IND', 'India');
INSERT INTO countries (id, iso2, iso3, country) VALUES (101, 'ID', 'IDN', 'Indonesia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (102, 'IR', 'IRN', 'Iran (Islamic Republic of Iran)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (103, 'IQ', 'IRQ', 'Iraq');
INSERT INTO countries (id, iso2, iso3, country) VALUES (104, 'IE', 'IRL', 'Ireland');
INSERT INTO countries (id, iso2, iso3, country) VALUES (105, 'IL', 'ISR', 'Israel');
INSERT INTO countries (id, iso2, iso3, country) VALUES (106, 'IT', 'ITA', 'Italy');
INSERT INTO countries (id, iso2, iso3, country) VALUES (107, 'JM', 'JAM', 'Jamaica');
INSERT INTO countries (id, iso2, iso3, country) VALUES (108, 'JP', 'JPN', 'Japan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (109, 'JO', 'JOR', 'Jordan (Hashemite Kingdom of Jordan)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (110, 'KZ', 'KAZ', 'Kazakhstan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (111, 'KE', 'KEN', 'Kenya');
INSERT INTO countries (id, iso2, iso3, country) VALUES (112, 'KI', 'KIR', 'Kiribati');
INSERT INTO countries (id, iso2, iso3, country) VALUES (113, 'KP', 'PRK', 'Korea (Democratic Peoples Republic pf [North] Korea)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (114, 'KR', 'KOR', 'Korea (Republic of [South] Korea)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (115, 'KW', 'KWT', 'Kuwait');
INSERT INTO countries (id, iso2, iso3, country) VALUES (116, 'KG', 'KGZ', 'Kyrgyzstan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (117, 'LA', 'LAO', 'Lao People''s Democratic Republic');
INSERT INTO countries (id, iso2, iso3, country) VALUES (118, 'LV', 'LVA', 'Latvia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (119, 'LB', 'LBN', 'Lebanon');
INSERT INTO countries (id, iso2, iso3, country) VALUES (120, 'LS', 'LSO', 'Lesotho');
INSERT INTO countries (id, iso2, iso3, country) VALUES (121, 'LR', 'LBR', 'Liberia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (122, 'LY', 'LBY', 'Libya (Libyan Arab Jamahirya)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (123, 'LI', 'LIE', 'Liechtenstein (Fürstentum Liechtenstein)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (124, 'LT', 'LTU', 'Lithuania');
INSERT INTO countries (id, iso2, iso3, country) VALUES (125, 'LU', 'LUX', 'Luxembourg');
INSERT INTO countries (id, iso2, iso3, country) VALUES (126, 'MO', 'MAC', 'Macao (Special Administrative Region of China)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (127, 'MK', 'MKD', 'Macedonia (Former Yugoslav Republic of Macedonia)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (128, 'MG', 'MDG', 'Madagascar');
INSERT INTO countries (id, iso2, iso3, country) VALUES (129, 'MW', 'MWI', 'Malawi');
INSERT INTO countries (id, iso2, iso3, country) VALUES (130, 'MY', 'MYS', 'Malaysia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (131, 'MV', 'MDV', 'Maldives');
INSERT INTO countries (id, iso2, iso3, country) VALUES (132, 'ML', 'MLI', 'Mali');
INSERT INTO countries (id, iso2, iso3, country) VALUES (133, 'MT', 'MLT', 'Malta');
INSERT INTO countries (id, iso2, iso3, country) VALUES (134, 'MH', 'MHL', 'Marshall Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (135, 'MQ', 'MTQ', 'Martinique');
INSERT INTO countries (id, iso2, iso3, country) VALUES (136, 'MR', 'MRT', 'Mauritania');
INSERT INTO countries (id, iso2, iso3, country) VALUES (137, 'MU', 'MUS', 'Mauritius');
INSERT INTO countries (id, iso2, iso3, country) VALUES (138, 'YT', 'MYT', 'Mayotte');
INSERT INTO countries (id, iso2, iso3, country) VALUES (139, 'MX', 'MEX', 'Mexico');
INSERT INTO countries (id, iso2, iso3, country) VALUES (140, 'FM', 'FSM', 'Micronesia (Federated States of Micronesia)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (141, 'MD', 'MDA', 'Moldova');
INSERT INTO countries (id, iso2, iso3, country) VALUES (142, 'MC', 'MCO', 'Monaco');
INSERT INTO countries (id, iso2, iso3, country) VALUES (143, 'MN', 'MNG', 'Mongolia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (144, 'MS', 'MSR', 'Montserrat');
INSERT INTO countries (id, iso2, iso3, country) VALUES (145, 'MA', 'MAR', 'Morocco');
INSERT INTO countries (id, iso2, iso3, country) VALUES (146, 'MZ', 'MOZ', 'Mozambique (Moçambique)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (147, 'MM', 'MMR', 'Myanmar (formerly Burma)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (148, 'NA', 'NAM', 'Namibia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (149, 'NR', 'NRU', 'Nauru');
INSERT INTO countries (id, iso2, iso3, country) VALUES (150, 'NP', 'NPL', 'Nepal');
INSERT INTO countries (id, iso2, iso3, country) VALUES (151, 'NL', 'NLD', 'Netherlands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (152, 'AN', 'ANT', 'Netherlands Antilles');
INSERT INTO countries (id, iso2, iso3, country) VALUES (153, 'NC', 'NCL', 'New Caledonia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (154, 'NZ', 'NZL', 'New Zealand');
INSERT INTO countries (id, iso2, iso3, country) VALUES (155, 'NI', 'NIC', 'Nicaragua');
INSERT INTO countries (id, iso2, iso3, country) VALUES (156, 'NE', 'NER', 'Niger');
INSERT INTO countries (id, iso2, iso3, country) VALUES (157, 'NG', 'NGA', 'Nigeria');
INSERT INTO countries (id, iso2, iso3, country) VALUES (158, 'NU', 'NIU', 'Niue');
INSERT INTO countries (id, iso2, iso3, country) VALUES (159, 'NF', 'NFK', 'Norfolk Island');
INSERT INTO countries (id, iso2, iso3, country) VALUES (160, 'MP', 'MNP', 'Northern Mariana Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (161, 'NO', 'NOR', 'Norway');
INSERT INTO countries (id, iso2, iso3, country) VALUES (162, 'OM', 'OMN', 'Oman');
INSERT INTO countries (id, iso2, iso3, country) VALUES (163, 'PK', 'PAK', 'Pakistan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (164, 'PW', 'PLW', 'Palau');
INSERT INTO countries (id, iso2, iso3, country) VALUES (165, 'PS', 'PSE', 'Palestinian Territories');
INSERT INTO countries (id, iso2, iso3, country) VALUES (166, 'PA', 'PAN', 'Panama');
INSERT INTO countries (id, iso2, iso3, country) VALUES (167, 'PG', 'PNG', 'Papua New Guinea');
INSERT INTO countries (id, iso2, iso3, country) VALUES (168, 'PY', 'PRY', 'Paraguay');
INSERT INTO countries (id, iso2, iso3, country) VALUES (169, 'PE', 'PER', 'Peru');
INSERT INTO countries (id, iso2, iso3, country) VALUES (170, 'PH', 'PHL', 'Philippines');
INSERT INTO countries (id, iso2, iso3, country) VALUES (171, 'PN', 'PCN', 'Pitcairn');
INSERT INTO countries (id, iso2, iso3, country) VALUES (172, 'PL', 'POL', 'Poland');
INSERT INTO countries (id, iso2, iso3, country) VALUES (173, 'PT', 'PRT', 'Portugal');
INSERT INTO countries (id, iso2, iso3, country) VALUES (174, 'PR', 'PRI', 'Puerto Rico');
INSERT INTO countries (id, iso2, iso3, country) VALUES (175, 'QA', 'QAT', 'Qatar');
INSERT INTO countries (id, iso2, iso3, country) VALUES (176, 'RE', 'REU', 'RÉunion');
INSERT INTO countries (id, iso2, iso3, country) VALUES (177, 'RO', 'ROU', 'Romania');
INSERT INTO countries (id, iso2, iso3, country) VALUES (178, 'RU', 'RUS', 'Russian Federation');
INSERT INTO countries (id, iso2, iso3, country) VALUES (179, 'RW', 'RWA', 'Rwanda');
INSERT INTO countries (id, iso2, iso3, country) VALUES (180, 'SH', 'SHN', 'Saint Helena');
INSERT INTO countries (id, iso2, iso3, country) VALUES (181, 'KN', 'KNA', 'Saint Kitts and Nevis');
INSERT INTO countries (id, iso2, iso3, country) VALUES (182, 'LC', 'LCA', 'Saint Lucia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (183, 'PM', 'SPM', 'Saint Pierre and Miquelon');
INSERT INTO countries (id, iso2, iso3, country) VALUES (184, 'VC', 'VCT', 'Saint Vincent and the Grenadines');
INSERT INTO countries (id, iso2, iso3, country) VALUES (185, 'WS', 'WSM', 'Samoa (formerly Western Samoa)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (186, 'SM', 'SMR', 'San Marino (Republic of)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (187, 'ST', 'STP', 'Sao Tome and Principe');
INSERT INTO countries (id, iso2, iso3, country) VALUES (188, 'SA', 'SAU', 'Saudi Arabia (Kingdom of Saudi Arabia)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (189, 'SN', 'SEN', 'Senegal');
INSERT INTO countries (id, iso2, iso3, country) VALUES (190, 'CS', 'SCG', 'Serbia and Montenegro (formerly Yugoslavia)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (191, 'SC', 'SYC', 'Seychelles');
INSERT INTO countries (id, iso2, iso3, country) VALUES (192, 'SL', 'SLE', 'Sierra Leone');
INSERT INTO countries (id, iso2, iso3, country) VALUES (193, 'SG', 'SGP', 'Singapore');
INSERT INTO countries (id, iso2, iso3, country) VALUES (194, 'SK', 'SVK', 'Slovakia (Slovak Republic)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (195, 'SI', 'SVN', 'Slovenia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (196, 'SB', 'SLB', 'Solomon Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (197, 'SO', 'SOM', 'Somalia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (198, 'ZA', 'ZAF', 'South Africa (zuid Afrika)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (199, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (200, 'ES', 'ESP', 'Spain (españa)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (201, 'LK', 'LKA', 'Sri Lanka');
INSERT INTO countries (id, iso2, iso3, country) VALUES (202, 'SD', 'SDN', 'Sudan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (203, 'SR', 'SUR', 'Suriname');
INSERT INTO countries (id, iso2, iso3, country) VALUES (204, 'SJ', 'SJM', 'Svalbard and Jan Mayen');
INSERT INTO countries (id, iso2, iso3, country) VALUES (205, 'SZ', 'SWZ', 'Swaziland');
INSERT INTO countries (id, iso2, iso3, country) VALUES (206, 'SE', 'SWE', 'Sweden');
INSERT INTO countries (id, iso2, iso3, country) VALUES (207, 'CH', 'CHE', 'Switzerland (Confederation of Helvetia)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (208, 'SY', 'SYR', 'Syrian Arab Republic');
INSERT INTO countries (id, iso2, iso3, country) VALUES (209, 'TW', 'TWN', 'Taiwan ("Chinese Taipei" for IOC)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (210, 'TJ', 'TJK', 'Tajikistan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (211, 'TZ', 'TZA', 'Tanzania');
INSERT INTO countries (id, iso2, iso3, country) VALUES (212, 'TH', 'THA', 'Thailand');
INSERT INTO countries (id, iso2, iso3, country) VALUES (213, 'TL', 'TLS', 'Timor-Leste (formerly East Timor)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (214, 'TG', 'TGO', 'Togo');
INSERT INTO countries (id, iso2, iso3, country) VALUES (215, 'TK', 'TKL', 'Tokelau');
INSERT INTO countries (id, iso2, iso3, country) VALUES (216, 'TO', 'TON', 'Tonga');
INSERT INTO countries (id, iso2, iso3, country) VALUES (217, 'TT', 'TTO', 'Trinidad and Tobago');
INSERT INTO countries (id, iso2, iso3, country) VALUES (218, 'TN', 'TUN', 'Tunisia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (219, 'TR', 'TUR', 'Turkey');
INSERT INTO countries (id, iso2, iso3, country) VALUES (220, 'TM', 'TKM', 'Turkmenistan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (221, 'TC', 'TCA', 'Turks and Caicos Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (222, 'TV', 'TUV', 'Tuvalu');
INSERT INTO countries (id, iso2, iso3, country) VALUES (223, 'UG', 'UGA', 'Uganda');
INSERT INTO countries (id, iso2, iso3, country) VALUES (224, 'UA', 'UKR', 'Ukraine');
INSERT INTO countries (id, iso2, iso3, country) VALUES (225, 'AE', 'ARE', 'United Arab Emirates');
INSERT INTO countries (id, iso2, iso3, country) VALUES (226, 'GB', 'GBR', 'United Kingdom (Great Britain)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (227, 'US', 'USA', 'United States');
INSERT INTO countries (id, iso2, iso3, country) VALUES (228, 'UM', 'UMI', 'United States Minor Outlying Islands');
INSERT INTO countries (id, iso2, iso3, country) VALUES (229, 'UY', 'URY', 'Uruguay');
INSERT INTO countries (id, iso2, iso3, country) VALUES (230, 'UZ', 'UZB', 'Uzbekistan');
INSERT INTO countries (id, iso2, iso3, country) VALUES (231, 'VU', 'VUT', 'Vanuatu');
INSERT INTO countries (id, iso2, iso3, country) VALUES (232, 'VA', 'VAT', 'Vatican City (Holy See)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (233, 'VE', 'VEN', 'Venezuela');
INSERT INTO countries (id, iso2, iso3, country) VALUES (234, 'VN', 'VNM', 'Viet Nam');
INSERT INTO countries (id, iso2, iso3, country) VALUES (235, 'VG', 'VGB', 'Virgin Islands, British');
INSERT INTO countries (id, iso2, iso3, country) VALUES (236, 'VI', 'VIR', 'Virgin Islands, U.S.');
INSERT INTO countries (id, iso2, iso3, country) VALUES (237, 'WF', 'WLF', 'Wallis and Futuna');
INSERT INTO countries (id, iso2, iso3, country) VALUES (238, 'EH', 'ESH', 'Western Sahara (formerly Spanish Sahara)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (239, 'YE', 'YEM', 'Yemen (Arab Republic)');
INSERT INTO countries (id, iso2, iso3, country) VALUES (240, 'ZM', 'ZMB', 'Zambia');
INSERT INTO countries (id, iso2, iso3, country) VALUES (241, 'ZW', 'ZWE', 'Zimbabwe');