<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>

    /* override styles when printing */
    @media print {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }

    @page {
        size: 8.27in 11.69in;  /* width height A4 size paper */
    }


    .item-list thead th,
    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
    }

    .heading td {
        min-height: 25px !important;
    }

    .heading tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }
</style>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Preview</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <!--            <button type="button" class="btn btn-tool" data-card-widget="remove">-->
            <!--                <i class="fa fa-times"></i>-->
            <!--            </button>-->
        </div>
    </div>
    <div class="card-body">
        <div style="width: 100%">
            <?php
            if ($data) {
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => FALSE, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div>";

            $customer = Customers::model()->findByPk($data->customer_id);
            ?>
        </div>
        <div class='printAllTableForThisReport' style="width: 100%;">
            <table style="width: 100%; border-collapse: collapse; font-size: 11px;" class="item-list">
                <tr>
                    <td colspan="2" style="border: 1px solid white;">
                        <img src="<?= Yii::app()->theme->baseUrl . "/images/logo.png" ?>"
                             style="width: 130px; height: 100px; float: left" alt="">
                    </td>
                    <td style="text-align: center; border: 1px solid white;" colspan="3"><h5>WARRANTY/REPLACEMENT</h5></td>
                </tr>
                <tr>
                    <td colspan="2" style="border-right: white; text-align: left; border-left: 1px solid white; border-right: 1px solid white; background: white;">
                        <h5>Customer Details</h5>
                        <?php
                        $customer_name = $customer_zip = $customer_city = $customer_state = $customer_phone = $customer_trn_no = "N/A";
                        if ($customer) {
                            $customer_name = $customer->company_name;
                            $customer_address = $customer->company_address;
                        }
                        echo "<b>$customer_name ( $customer->id)</b><br>";
                        echo "$customer_address";
                        ?>
                    </td>
                    <td colspan="3" style="border-right: 1px solid white;">
                        <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
                            <tr>
                                <td style="text-align: center;"><b>Return No</b></td>
                                <td style="text-align: center;"><b>Date</b></td>
                            </tr>
                            <tr>
                                <td style="text-align: center;"><?= "$data->id" ?></td>
                                <td style="text-align: center;"><?= date('d.m.Y', strtotime($data->return_date)) ?></td>
                            </tr>
                        </table>
                    </td>
                </tr>

                <tr>
                    <td style="text-align: center;">#</td>
                    <td style="text-align: center;" colspan="2">Description</td>
                    <td style="text-align: center; width: 10%;">Qty</td>
                </tr>
                <tbody>
                <?php
                $vat = 0;
                $criteria = new CDbCriteria();
                $criteria->select = "t.*, pm.model_name as model_name";
                $criteria->addColumnCondition(array('return_id' => $data->id));
                $criteria->join = " LEFT JOIN prod_models pm ON pm.id = t.model_id ";
                $data2 = SellReturnDetails::model()->findAll($criteria);
                $row_total = 0;
                if ($data2) {
                    $i = 1;
                    foreach ($data2 as $dt) {
                        ?>
                        <tr>
                            <td style="text-align: center; width: 50px;"><?= $i++ ?></td>
                            <td colspan="2" style="text-align: left;">
                                <?= $dt->model_name ?>
                                <?php
                                if (strlen($dt->product_sl_no) > 0) {
                                    echo "<br><br>$dt->product_sl_no";
                                }
                                ?>
                            </td>
                            <td style="text-align: center;"><?= number_format($dt->return_qty, 2) ?></td>
                        </tr>
                        <?php
                        $row_total += $dt->row_total;
                    }
                } else {
                    ?>
                    <tr>
                        <td colspan="6">
                            <div class="alert alert-danger" role="alert">
                                No item found
                            </div>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                <tr>
                    <td colspan="4" style="height: 150px; vertical-align: bottom; text-align: left; border: 1px solid white; background: white;">
                        <div style=" width: 50%; float:left; clear:right;">
                            <span style="text-decoration: overline;">Receivers Name, Signature & Mob No</span>
                        </div>

                        <div style=" width: 50%; float: right; text-align:right;">
                            <span style="text-decoration: overline; ">Created By: <span style="text-transform: uppercase;"><?= Users::model()->findByPk($data->created_by)->username ?></span></span>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <?php
        } else {
            ?>
            <div class="alert alert-danger" role="alert">
                No result found!
            </div>
            <?php
        }
        ?>
    </div>
</div>