<link rel="stylesheet" href="<?php echo Yii::app()->theme->baseUrl; ?>/css/report.css" type="text/css" media="screen"/>

<style>

    /* override styles when printing */
    @media print {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }

        .page-break-div {
            page-break-after: always !important;
        }
    }


    @media screen {
        .printAllTableForThisReport {
            font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
            font-size: 12px;
        }
    }

    @page {
        size: 8.27in 11.69in;  /* width height A4 size paper */
    }


    .item-list thead th,
    .item-list tbody th,
    .item-list tbody td {
        border: 1px solid black;
    }

    .heading td {
        min-height: 25px !important;
    }

    .heading tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(even) {
        background: #f5f5f5;
    }

    .item-list tbody tr:nth-child(odd) {
        background: white;
    }

    hr {
        border: 0;
        clear: both;
        display: block;
        width: 96%;
        background-color: black;
        height: 1px;
    }
</style>

<div class="card card-success">
    <div class="card-header">
        <h3 class="card-title">Preview</h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <!--            <button type="button" class="btn btn-tool" data-card-widget="remove">-->
            <!--                <i class="fa fa-times"></i>-->
            <!--            </button>-->
        </div>
    </div>
    <div class="card-body">
        <div style="width: 100%">
            <?php
            if ($data) {
            echo "<div class='printBtn' style='float: left; clear:right; width: 10%;'>";
            $this->widget('ext.mPrint.mPrint', array(
//             'title' => 'Report generated by: '.Yii::app()->user->name. ' ' . ' =====  ' .Yii::app()->name.'',
                'title' => ' ', //the title of the document. Defaults to the HTML title
                'tooltip' => 'Print', //tooltip message of the print icon. Defaults to 'print'
                'text' => '', //text which will appear beside the print icon. Defaults to NULL
                'element' => '.printAllTableForThisReport', //the element to be printed.
                'exceptions' => array(//the element/s which will be ignored
                    '.summary',
                    '.search-form',
                    '#excludeDiv',
                ),
                'publishCss' => FALSE, //publish the CSS for the whole page?
                'visible' => !Yii::app()->user->isGuest, //should this be visible to the current user?
                'alt' => 'print', //text which will appear if image can't be loaded
                'debug' => FALSE, //enable the debugger to see what you will get
                'id' => 'print-div'         //id of the print link
            ));
            echo "</div>";
            $yourCompany = YourCompany::model()->findByAttributes(['is_active' => YourCompany::ACTIVE]);
            $company_name = $company_location = $company_road = $company_house = $company_contact = $company_email = $company_web = $company_trn_no = "N/A";
            if ($yourCompany) {
                $company_name = $yourCompany->company_name;
                $company_location = $yourCompany->location;
                $company_road = $yourCompany->road;
                $company_house = $yourCompany->house;
                $company_contact = $yourCompany->contact;
                $company_email = $yourCompany->email;
                $company_web = $yourCompany->web;
                $company_trn_no = $yourCompany->trn_no;
            }
            ?>
        </div>
        <?php
        foreach ($data as $dt) {
            ?>
            <div class='printAllTableForThisReport' style="width: 8.5in;">
                <table style="width: 100%; border-collapse: collapse; font-size: 15px;" class="item-list">
                    <tr>
                        <td>
                            <div style="width: 100%; float: left; clear: right;">
                                <div style="width: 70%; float: left; clear: right;">
                                    <img src="<?= Yii::app()->theme->baseUrl . "/images/logo.png" ?>"
                                         style="width: 130px; height: 100px;">
                                </div>
                                <div style="float: right; width: 29%;">
                                    <div style="float: right;">Tel.: <?= $company_contact ?> </div>
                                    <br>
                                    <div style="float: right;  text-align: right;">
                                        <?= $company_house ?>
                                    </div>
                                    <br>
                                    <div style="float: right; text-align: right;"> <?= $company_road ?></div>
                                    <br>
                                    <div style="float: right;  text-align: right;"> <?= $company_location ?></div>
                                </div>
                            </div>
                            <hr>
                            <div style="width: 100%; float: left; clear: right;">
                                <div style="width: 33%; text-align: center; float: left;clear:right; vertical-align: middle;">
                                    <img src="<?= Yii::app()->theme->baseUrl . "/images/globe_icon.png" ?>"
                                         style="width: 16px; height: 16px; vertical-align: middle;">
                                    <?= $company_web ?>
                                </div>
                                <div style="width: 33%; text-align: center; float: left;clear:right; vertical-align: middle;">
                                    <img src="<?= Yii::app()->theme->baseUrl . "/images/email.png" ?>"
                                         style="width: 16px; height: 16px; vertical-align: middle;">
                                    <?= $company_email ?>
                                </div>
                                <div style="width: 33%; text-align: center; float: left;clear:right; vertical-align: middle;">
                                    <img src="<?= Yii::app()->theme->baseUrl . "/images/email.png" ?>"
                                         style="width: 16px; height: 16px; vertical-align: middle;">
                                    sales@tmebd.com
                                </div>
                            </div>
                            <hr>
                            <div style="width: 100%; float: left; clear: right;">
                                <div style="width: 30%; float: left; clear: right;">
                                    <div style="width: 65%; float: left; clear: right;">
                                        <div style="float: left; clear: right; width: 70%;"></div>
                                        <div style="clear: right;"></div>
                                        <div style="width: 100%; height: 30px; border: 2px solid black"></div>
                                    </div>
                                    <div style="width: 34%; float: left; clear: right;">
                                        <div style="float: left; clear: right; width: 70%;"></div>
                                        <div style="clear: right;"></div>
                                        <div style="width: 100%; height: 30px; border: 2px solid black"></div>
                                    </div>
                                </div>
                                <div style="width: 38%; float: left; clear: right; text-align: center; vertical-align: middle;font-weight: bold;font-size: 18px;text-transform: uppercase;">
                                    <div>
                                        Receipt Voucher
                                    </div>
                                </div>
                                <div style="width: 30%; height: 55px; float: left; clear: right; vertical-align: bottom; text-align: right;">

                                    <div style="width: 100%; float: left; clear:right;">
                                        <b style="font-size: 14px; line-height: 30px; letter-spacing:2px"><?= $dt->mr_no; ?></b>
                                    </div>
                                    <div style="width: 100%; float: left; clear:right;">
                                        Date <span
                                                style="text-decoration: underline dotted;">&nbsp;&nbsp;&nbsp;<?= date('d.M.Y', strtotime($dt->date)) ?> &nbsp;&nbsp;</span>&nbsp;&nbsp;
                                    </div>
                                </div>
                            </div>
                            <div style="width: 100%; float: left; clear: right;">
                                <div class="mr-row" style="padding-top: 22px; float: left; clear: right; width: 100%;">
                                    <div style="width: 22%; float: left; clear: right;">
                                        Received from Mr. / M/s
                                    </div>
                                    <div style="width: 77%; float: left; clear: right; border-bottom: 1px dotted black;">
                                        &nbsp;&nbsp;&nbsp;<?= Customers::model()->nameOfThis($dt->customer_id) ?>&nbsp;&nbsp;&nbsp;
                                    </div>
                                </div>
                                <div class="mr-row" style="padding-top: 20px; float: left; clear: right; width: 100%;">
                                    <div style="width: 20%; float: left; clear: right;">The sum of Dhs</div>
                                    <div style="width: 78%; float: left; clear: right; border-bottom: 1px dotted black; text-align: center;">
                                        &nbsp;&nbsp;&nbsp;<?= number_format($dt->amount, 2) ?>/=&nbsp;&nbsp;&nbsp;
                                    </div>
                                </div>
                                <div class="mr-row" style="padding-top: 20px; float: left; clear: right; width: 100%;">
                                    <div style="width: 65%; float: left; clear: right;">
                                        <div style="width: 24%; float: left; clear: right;">Cash/Cheque No</div>
                                        <div style="width: 74%; float: left; clear: right; border-bottom: 1px dotted black; text-align: center;">
                                            &nbsp;&nbsp;&nbsp;<?= $dt->cheque_no == "" ? "N/A" : $dt->cheque_no ?>&nbsp;&nbsp;&nbsp;
                                        </div>
                                    </div>
                                    <div style="width: 34%; float: left; clear: right;">
                                        <div style="width: 15%; float: left; clear: right;">&nbsp;&nbsp;Date</div>
                                        <div style="width: 75%; float: left; clear: right; border-bottom: 1px dotted black; text-align: center;">
                                            &nbsp;&nbsp;&nbsp;<?= $dt->cheque_date != "" ? date('d.M.y', strtotime($dt->cheque_date)) : "N/A" ?>
                                            &nbsp;&nbsp;&nbsp;
                                        </div>
                                    </div>
                                </div>

                                <div class="mr-row" style="padding-top: 20px; float: left; clear: right; width: 100%;">
                                    <div style="width: 10%; float: left; clear: right;">Bank</div>
                                    <div style="width: 88%; float: left; clear: right; border-bottom: 1px dotted black; text-align: center;">
                                        &nbsp;&nbsp;&nbsp;<?= CrmBank::model()->nameOfThis($dt->bank_id) ?>&nbsp;&nbsp;&nbsp;
                                    </div>
                                </div>

                                <div class="mr-row" style="padding-top: 20px; float: left; clear: right; width: 100%;">
                                    <div style="width: 10%; float: left; clear: right;">Being</div>
                                    <div style="width: 88%; float: left; clear: right; border-bottom: 1px dotted black; text-align: center;">
                                        &nbsp;&nbsp;&nbsp;<?= $dt->remarks ?>&nbsp;&nbsp;&nbsp;
                                    </div>
                                </div>
                                <div class="mr-row" style="padding-top: 20px; float: left; clear: right; width: 100%;">
                                    <div style="width: 100%; float: left; clear: right; border-bottom: 1px dotted black; text-align: center;">
                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                    </div>
                                </div>
                            </div>

                            <div style="width: 100%; float: left; clear: right; margin-top: 55px; font-weight: bold;">
                                <div style="width: 50%; float: left; clear: right;">
                                    <div style="width: 25%; float: left; clear: right">
                                        Received By
                                    </div>
                                    <div style="width: 75%; float: left; clear: right; border-bottom: 1px dotted black;"><?= Users::model()->nameOfThis($dt->created_by) ?></div>
                                </div>
                                <div style="width: 50%; float: left; clear: right; text-align: center;">
                                    <span style="border-top: 1px dotted black;">FOR <?= strtoupper($company_name) ?></span>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
            <?php
        }
        } else {
            ?>
            <div class="alert alert-danger" role="alert">
                No result found!
            </div>
            <?php
        }
        ?>
    </div>
</div>